package com.tsuyu.line;

import android.Manifest;
import android.app.Activity;
import android.content.pm.PackageManager;
import android.os.Build;
import android.widget.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;

public final class DownloadActions {
    private DownloadActions(){}
    private interface Loader {List<ApiRepository.DownloadOption> load()throws Exception;}
    private static final class VoicePack {Anime.Playback ready;String[] names,values;}
    public static void askEpisode(Activity activity,Anime anime,Anime.Playback current,double suggested){chooseEpisodeFast(activity,anime,current,suggested,null);}
    public static void chooseEpisode(Activity activity,Anime anime,Anime.Playback current,double suggested){chooseEpisodeFast(activity,anime,current,suggested,null);}
    public static void chooseEpisodeFast(Activity activity,Anime anime,Anime.Playback current,double suggested,List<Anime.Episode> known){if(known!=null&&!known.isEmpty()){Anime.Playback ready=new Anime.Playback();ready.catalog=anime;ready.video=anime;ready.provider=anime.source;showEpisodeChoice(activity,anime,ready,new ArrayList<>(known),suggested);return;}if(current!=null&&current.video!=null&&!current.video.episodeList.isEmpty()){showEpisodeChoice(activity,anime,current,new ArrayList<>(current.video.episodeList),suggested);return;}YoruApp.app().io.execute(()->{try{Anime.Playback ready=YoruApp.app().api.playback(anime,"yoru");ArrayList<Anime.Episode> episodes=ready==null||ready.video==null?new ArrayList<>():new ArrayList<>(ready.video.episodeList);YoruApp.app().main.post(()->{if(dead(activity))return;showEpisodeChoice(activity,anime,ready,episodes,suggested);});}catch(Exception e){YoruApp.app().main.post(()->{if(!dead(activity))Ui.toast(activity,"Список серий пока недоступен");});}});}
    private static void showEpisodeChoice(Activity activity,Anime anime,Anime.Playback ready,ArrayList<Anime.Episode> episodes,double suggested){episodes.removeIf(e->e==null);if(episodes.isEmpty()){Ui.toast(activity,"Нет вышедших серий для скачивания");return;}String[] labels=labels(episodes);int index=closest(episodes,suggested);Ui.singleChoice(activity,"Выберите серию",labels,index,"Далее",i->{Anime.Episode ep=episodes.get(i);if(ep.future)ScheduledDownloads.choose(activity,anime,ep.number,0,ep.airDate);else prepare(activity,anime,ready,ep.number);});}
    public static void chooseBatch(Activity activity,Anime anime,Anime.Playback current,double suggested){chooseBatchFast(activity,anime,current,suggested,null);}
    public static void chooseBatchFast(Activity activity,Anime anime,Anime.Playback current,double suggested,List<Anime.Episode> known){if((current==null||current.video==null||current.video.episodeList.isEmpty())&&known!=null&&!known.isEmpty()){Anime.Playback ready=new Anime.Playback();ready.catalog=anime;ready.video=anime;ready.provider=anime.source;showBatch(activity,anime,ready,new ArrayList<>(known),suggested);return;}TaskQueue.Signal cancelled=new TaskQueue.Signal();Ui.Progress wait=Ui.progress(activity,"Готовим серии…",true,()->cancelled.set(true));TaskQueue.run(YoruApp.app().io,cancelled,()->{try{Anime.Playback ready=current;if(ready==null||ready.video==null||ready.video.episodeList.isEmpty())ready=YoruApp.app().api.playback(anime,"yoru");Anime.Playback finalReady=ready;ArrayList<Anime.Episode> episodes=new ArrayList<>(ready.video.episodeList);YoruApp.app().main.post(()->{if(dead(activity)||cancelled.get())return;wait.dismiss();if(episodes.isEmpty()){Ui.toast(activity,"Список серий пока недоступен");return;}showBatch(activity,anime,finalReady,episodes,suggested);});}catch(Exception e){YoruApp.app().main.post(()->{if(!dead(activity)&&!cancelled.get()){wait.dismiss();Ui.toast(activity,"Не удалось загрузить список серий");}});}},()->{wait.dismiss();Ui.toast(activity,"Очередь занята Повторите действие позже");});}
    public static void prepare(Activity activity,Anime anime,Anime.Playback current,double episode){loadVoiceDialog(activity,anime,current,episode);}
    public static void prepareNativeCurrent(Activity activity,Anime anime,Anime.Playback current,double number,Anime.Episode episode,String voice,String player){loadAndShow(activity,anime,number,"Готовим текущую озвучку…","Текущую озвучку пока нельзя сохранить",()->merge(nativeOptions(anime,number,episode,voice,player)));}
    private static void loadVoiceDialog(Activity activity,Anime anime,Anime.Playback current,double episode){TaskQueue.Signal cancelled=new TaskQueue.Signal();Ui.Progress wait=Ui.progress(activity,"Открываем серию…",true,()->cancelled.set(true));TaskQueue.run(YoruApp.app().io,cancelled,()->{try{VoicePack pack=voicePack(anime,current,episode);YoruApp.app().main.post(()->{if(dead(activity)||cancelled.get())return;wait.dismiss();filterDialog(activity,anime,pack.ready,episode,pack);});}catch(Exception e){YoruApp.app().main.post(()->{if(!dead(activity)&&!cancelled.get()){wait.dismiss();Ui.toast(activity,"Не удалось загрузить доступные озвучки");}});}},()->{wait.dismiss();Ui.toast(activity,"Очередь занята Повторите действие позже");});}
    private static VoicePack voicePack(Anime anime,Anime.Playback current,double episode)throws Exception{Anime.Playback ready=current;if(ready==null||ready.video==null||ready.video.episodeList.isEmpty())ready=YoruApp.app().api.playback(anime,"yoru");LinkedHashMap<String,String> voices=new LinkedHashMap<>();if(ready!=null&&ready.video!=null){Anime.Episode ep=findEpisode(ready.video,episode);String direct=ApiRepository.sourceVoice(ready.video.source);if(ep!=null){for(Anime.Variant v:ep.variants){String title=ApiRepository.voiceTitle(v.name.isEmpty()?v.label():v.name);String key=ApiRepository.voiceKey(title);if(!key.isEmpty()&&!voices.containsKey(key))voices.put(key,title);}if(!direct.isEmpty()&&!ep.streams.isEmpty())voices.put(ApiRepository.voiceKey(direct),direct);}}ArrayList<String> names=new ArrayList<>(),values=new ArrayList<>();names.add("Любая доступная");values.add("");for(String title:voices.values()){names.add(title);values.add(title);}VoicePack pack=new VoicePack();pack.ready=ready;pack.names=names.toArray(new String[0]);pack.values=values.toArray(new String[0]);return pack;}
    private static Anime.Episode findEpisode(Anime anime,double number){if(anime==null)return null;Anime.Episode fallback=null;double best=Double.MAX_VALUE;for(Anime.Episode ep:anime.episodeList){if(ep==null)continue;if(Math.abs(ep.number-number)<0.001)return ep;double diff=Math.abs(ep.number-number);if(diff<best){best=diff;fallback=ep;}}return fallback;}
    private static void filterDialog(Activity activity,Anime anime,Anime.Playback current,double episode,VoicePack pack){LinearLayout col=Ui.column(activity);col.setPadding(Ui.dp(activity,4),0,Ui.dp(activity,4),0);int voiceIndex=voiceIndex(ownVoice(anime),pack.values);Spinner voice=spinner(activity,col,"Озвучка",pack.names,voiceIndex);Switch strict=new Switch(activity);strict.setText("Показывать только выбранную озвучку");strict.setTextColor(Ui.TEXT);strict.setTextSize(13);strict.setTypeface(Ui.typeface(activity,false));strict.setChecked(YoruApp.app().store.onlyPreferredVoice()&&voiceIndex>0);col.addView(strict,Ui.lp(activity,-1,50));String[] qLabels=QualityPlus.LABELS_WITH_BEST;int[] qValues=QualityPlus.valuesWithBest();int q=YoruApp.app().store.downloadResolution(),qIndex=QualityPlus.index(q);Spinner quality=spinner(activity,col,"Разрешение",qLabels,qIndex);TextView now=Ui.text(activity,"На кнопках сейчас: "+(voiceIndex>0?pack.names[voiceIndex]:"выбор озвучки"),10,Ui.PURPLE,false);col.addView(now);Ui.space(col,6);TextView note=Ui.text(activity,"Список озвучек собран именно для этой серии Tsuyu проверит только выбранную озвучку и нужное разрешение",10,Ui.MUTED,false);col.addView(note);Ui.custom(activity,"Скачивание серии "+Ui.number(episode),col,"Найти",()->{String selectedVoice=pack.values[voice.getSelectedItemPosition()];int selectedQuality=qValues[quality.getSelectedItemPosition()];boolean only=strict.isChecked()&&!selectedVoice.isEmpty();if(!selectedVoice.isEmpty()){YoruApp.app().store.setVoiceFor(anime,selectedVoice);YoruApp.app().store.rememberVoice(selectedVoice);}else YoruApp.app().store.setVoiceFor(anime,"");YoruApp.app().store.onlyPreferredVoice(only);if(selectedQuality<QualityPlus.BEST)YoruApp.app().store.downloadResolution(selectedQuality);loadAndShow(activity,anime,episode,"Ищем подходящую озвучку…","Tsuyu не нашёл выбранную озвучку для сохранения этой серии Измените фильтр или откройте серию и попробуйте текущую озвучку",selectedQuality,()->YoruApp.app().api.downloadOptions(anime,current,episode,selectedVoice,selectedQuality,only));},null,null,"Отмена");}
    private static String ownVoice(Anime anime){try{String own=YoruApp.app().store.voiceFor(anime);return own.isEmpty()?YoruApp.app().store.voicePreference():own;}catch(Exception e){return "";}}     private static int voiceIndex(String value){return voiceIndex(value,ApiRepository.VOICE_PREF_VALUES);}
    private static int voiceIndex(String value,String[] values){String key=ApiRepository.voiceKey(value);for(int i=0;i<values.length;i++)if(ApiRepository.voiceKey(values[i]).equals(key))return i;return 0;}
    private static Spinner spinner(Activity activity,LinearLayout col,String title,String[] values,int initial){col.addView(Ui.text(activity,title,11,Ui.MUTED,false));Spinner s=new Spinner(activity);s.setAdapter(new ArrayAdapter<>(activity,android.R.layout.simple_spinner_dropdown_item,values));s.setSelection(Math.max(0,Math.min(values.length-1,initial)));col.addView(s,Ui.lp(activity,-1,45));Ui.space(col,8);return s;}
    private static void showBatch(Activity activity,Anime anime,Anime.Playback ready,ArrayList<Anime.Episode> episodes,double suggested){String[] presets={"Следующие 3 серии","Следующие 6 серий","Следующие 12 серий","Выбрать серии вручную"};Ui.choices(activity,"Массовое скачивание",presets,which->{if(which==3)multiBatch(activity,anime,ready,episodes,suggested);else{int count=which==0?3:which==1?6:12;int start=closest(episodes,suggested);ArrayList<Anime.Episode> selected=new ArrayList<>();for(int i=start;i<episodes.size()&&selected.size()<count;i++)selected.add(episodes.get(i));qualityBatch(activity,anime,ready,selected);}});}
    private static void multiBatch(Activity activity,Anime anime,Anime.Playback ready,ArrayList<Anime.Episode> episodes,double suggested){episodes.removeIf(e->e==null);if(episodes.isEmpty()){Ui.toast(activity,"Нет вышедших серий для скачивания");return;}String[] labels=labels(episodes);boolean[] checked=new boolean[episodes.size()];int start=closest(episodes,suggested);for(int i=0;i<episodes.size();i++)checked[i]=i>=start&&i<start+3;Ui.multiChoice(activity,"Выберите серии",labels,checked,"Разрешение",state->{ArrayList<Anime.Episode> selected=new ArrayList<>();for(int n=0;n<episodes.size();n++)if(state[n])selected.add(episodes.get(n));qualityBatch(activity,anime,ready,selected);});}
    private static void qualityBatch(Activity activity,Anime anime,Anime.Playback ready,ArrayList<Anime.Episode> episodes){episodes.removeIf(e->e==null);if(episodes.isEmpty()){Ui.toast(activity,"Нет вышедших серий для скачивания");return;}LinearLayout col=Ui.column(activity);col.setPadding(Ui.dp(activity,4),0,Ui.dp(activity,4),0);Spinner voice=spinner(activity,col,"Озвучка",ApiRepository.VOICE_PREF_NAMES,voiceIndex(ownVoice(anime)));Switch strict=new Switch(activity);strict.setText("Только выбранная озвучка");strict.setTextColor(Ui.TEXT);strict.setTextSize(13);strict.setTypeface(Ui.typeface(activity,false));strict.setChecked(YoruApp.app().store.onlyPreferredVoice());col.addView(strict,Ui.lp(activity,-1,50));String[] labels={"Как в настройках","360p или ниже","480p или ниже","720p или ниже","1080p или ниже","Лучшее доступное разрешение"};int[] values={-1,360,480,720,1080,QualityPlus.BEST};Spinner quality=spinner(activity,col,"Разрешение",labels,0);Ui.custom(activity,"Фильтры для "+episodes.size()+" серий",col,"Добавить",()->{String selectedVoice=ApiRepository.VOICE_PREF_VALUES[voice.getSelectedItemPosition()];boolean only=strict.isChecked()&&!selectedVoice.isEmpty();if(!selectedVoice.isEmpty()){YoruApp.app().store.setVoiceFor(anime,selectedVoice);YoruApp.app().store.rememberVoice(selectedVoice);}YoruApp.app().store.onlyPreferredVoice(only);startBatch(activity,anime,ready,episodes,values[quality.getSelectedItemPosition()],selectedVoice,only);},null,null,"Отмена");}
    private static void startBatch(Activity activity,Anime anime,Anime.Playback ready,ArrayList<Anime.Episode> episodes,int preferred,String voice,boolean strict){TaskQueue.Signal cancelled=new TaskQueue.Signal();Ui.Progress wait=Ui.progress(activity,"Готовим очередь: 0 / "+episodes.size(),true,()->cancelled.set(true));TaskQueue.run(YoruApp.app().io,cancelled,()->{int added=0,failed=0;for(int i=0;i<episodes.size()&&!cancelled.get();i++){Anime.Episode ep=episodes.get(i);int done=i+1;YoruApp.app().main.post(()->{if(!dead(activity))wait.setMessage("Готовим очередь: "+done+" / "+episodes.size());});try{int limit=preferred<0?YoruApp.app().store.downloadResolution():preferred;List<ApiRepository.DownloadOption> options=YoruApp.app().api.downloadOptions(anime,ready,ep.number,voice,limit,strict);ApiRepository.DownloadOption chosen=choose(options,preferred);if(chosen==null){failed++;continue;}added++;YoruApp.app().main.post(()->{if(!dead(activity))YoruApp.app().downloads().enqueue(anime,chosen.source,chosen.episode,chosen.quality);});Thread.sleep(100);}catch(Exception e){failed++;}}int a=added,f=failed;YoruApp.app().main.post(()->{if(dead(activity))return;wait.dismiss();Ui.toast(activity,"В очередь добавлено: "+a+(f>0?" · не найдено: "+f:""));});},()->{wait.dismiss();Ui.toast(activity,"Очередь занята Повторите действие позже");});}
    private static ApiRepository.DownloadOption choose(List<ApiRepository.DownloadOption> options,int preferred){if(options==null||options.isEmpty())return null;ApiRepository.DownloadOption best=null;if(preferred==9999){for(ApiRepository.DownloadOption o:options)if(best==null||o.quality>best.quality)best=o;return best==null?options.get(0):best;}int limit=preferred<0?(YoruApp.app().savingMobile()?360:YoruApp.app().store.quality()):preferred;for(ApiRepository.DownloadOption o:options)if(o.quality>0&&o.quality<=limit&&(best==null||o.quality>best.quality))best=o;if(best!=null)return best;for(ApiRepository.DownloadOption o:options)if(best==null||o.quality<best.quality)best=o;return best==null?options.get(0):best;}
    private static void loadAndShow(Activity activity,Anime anime,double episode,String message,String empty,Loader loader){loadAndShow(activity,anime,episode,message,empty,-1,loader);}
    private static void loadAndShow(Activity activity,Anime anime,double episode,String message,String empty,int preferredQuality,Loader loader){TaskQueue.Signal cancelled=new TaskQueue.Signal();Ui.Progress wait=Ui.progress(activity,message,true,()->cancelled.set(true));TaskQueue.run(YoruApp.app().io,cancelled,()->{try{List<ApiRepository.DownloadOption> options=merge(loader.load());YoruApp.app().main.post(()->{if(dead(activity)||cancelled.get())return;wait.dismiss();if(options.isEmpty()){Ui.message(activity,"Нет доступного варианта",empty);return;}showOptions(activity,anime,episode,options,preferredQuality);});}catch(Exception e){YoruApp.app().main.post(()->{if(!dead(activity)&&!cancelled.get()){wait.dismiss();Ui.toast(activity,"Не удалось подготовить загрузку Попробуйте другой вариант");}});}},()->{wait.dismiss();Ui.toast(activity,"Очередь занята Повторите действие позже");});}
    private static void showOptions(Activity activity,Anime anime,double episode,List<ApiRepository.DownloadOption> options,int preferredQuality){String[] labels=new String[options.size()];int preferred=preferredQuality>0?preferredQuality:(YoruApp.app().savingMobile()?480:YoruApp.app().store.quality()),index=0,best=-1;for(int i=0;i<options.size();i++){labels[i]=privateLabel(options.get(i));int q=options.get(i).quality;if(preferred==9999){if(q>best){best=q;index=i;}}else if(q>0&&q<=preferred&&q>best){best=q;index=i;}}Ui.singleChoice(activity,"Серия "+Ui.number(episode)+" · озвучка и разрешение",labels,index,"Скачать",i->confirm(activity,anime,options.get(i)));}
    private static List<ApiRepository.DownloadOption> nativeOptions(Anime anime,double number,Anime.Episode current,String voice,String player){ArrayList<ApiRepository.DownloadOption> out=new ArrayList<>();if(current==null||current.streams.isEmpty())return out;int n=0;for(Map.Entry<Integer,String> stream:current.streams.entrySet()){String safe=ApiRepository.safeUrl(stream.getValue());if(safe.isEmpty())continue;Anime source=copyAnime(anime,"yummy","native-"+Integer.toHexString((anime.key()+"|"+safe).hashCode()));Anime.Episode ep=new Anime.Episode();ep.id=source.id+"-"+Ui.number(number)+"-"+(++n);ep.number=number;ep.name=(voice==null||voice.isEmpty())?"Плеер Tsuyu":voice;ep.streams.put(stream.getKey(),safe);out.add(new ApiRepository.DownloadOption(source,ep,stream.getKey(),ep.name,(player==null||player.isEmpty())?"Плеер Tsuyu":"Плеер Tsuyu · "+player));}return out;}
    private static String privateLabel(ApiRepository.DownloadOption option){String size=Ui.videoSizeHint(option.quality,option.episode==null?0:option.episode.duration);return option.label()+" · "+size+" · без лишней проверки";}
    private static Anime copyAnime(Anime anime,String sourceId,String id){Anime source=new Anime();source.source=sourceId;source.id=id;source.title=anime.title;source.original=anime.original;source.poster=anime.poster;source.description=anime.description;source.year=anime.year;source.type=anime.type;source.status=anime.status;source.episodes=anime.episodes;source.episodesAired=anime.episodesAired;source.nextEpisodeAt=anime.nextEpisodeAt;source.malId=anime.malId;source.anilistId=anime.anilistId;source.kpId=anime.kpId;return source;}
    private static ArrayList<ApiRepository.DownloadOption> merge(List<ApiRepository.DownloadOption> options){LinkedHashMap<String,ApiRepository.DownloadOption> map=new LinkedHashMap<>();if(options!=null)for(ApiRepository.DownloadOption option:options){if(option==null||option.source==null||option.episode==null)continue;String url=option.episode.streams.get(option.quality);String safe=ApiRepository.safeUrl(url);if(safe.isEmpty())continue;String voice=ApiRepository.voiceKey(option.voice+" "+option.episode.name);String key=Ui.number(option.episode.number)+"|"+option.quality+"|"+(voice.isEmpty()?"unknown:"+Integer.toHexString(safe.hashCode()):voice);if(!map.containsKey(key))map.put(key,option);}return new ArrayList<>(map.values());}
    private static void confirm(Activity a,Anime anime,ApiRepository.DownloadOption option){Runnable run=()->{if(Build.VERSION.SDK_INT>=33&&a.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)a.requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},4101);YoruApp.app().downloads().enqueue(anime,option.source,option.episode,option.quality);};if(YoruApp.app().traffic.metered()&&!YoruApp.app().store.wifiDownloads())Ui.confirm(a,"Скачать через мобильную сеть?","Ориентир по размеру: "+Ui.videoSizeHint(option.quality,option.episode==null?0:option.episode.duration)+" Чтобы экономить трафик, включите загрузки только по Wi‑Fi в настройках","Скачать",run,"Отмена");else run.run();}
    private static String[] labels(ArrayList<Anime.Episode> episodes){String[] labels=new String[episodes.size()];for(int i=0;i<episodes.size();i++){Anime.Episode ep=episodes.get(i);labels[i]="Серия "+Ui.number(ep.number)+(ep.future?" · скачать после выхода":(ep.name.isEmpty()?"":" · "+ep.name));}return labels;}
    private static int closest(ArrayList<Anime.Episode> episodes,double suggested){int index=0;double best=Double.MAX_VALUE;for(int i=0;i<episodes.size();i++){double diff=Math.abs(episodes.get(i).number-suggested);if(diff<best){best=diff;index=i;}}return index;}
    private static boolean dead(Activity activity){return activity.isFinishing()||activity.isDestroyed();}
}
