package com.tsuyu.line;

import android.app.*;
import android.content.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

final class FeaturePanels {
    private FeaturePanels(){}

    static void tiktok(Activity a){try{a.startActivity(new Intent(a,TikTokActivity.class));}catch(Exception e){Ui.toast(a,"Не удалось открыть ленту");}}



    static void queue(Activity a){List<Anime> rows=YoruApp.app().store.watchQueue();ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,430)));if(rows.isEmpty()){col.addView(Ui.text(a,"План пуст Добавьте тайтл из карточки кнопкой “В план”",12,Ui.MUTED,false));}else{for(Anime anime:rows)animeLine(a,col,anime,YoruBrain.nextHint(anime),true);}Ui.custom(a,"План просмотра",sc,"Готово",null,rows.isEmpty()?null:"Очистить",()->{YoruApp.app().store.clearWatchQueue();Ui.toast(a,"План очищен");},null);}
    static void priorities(Activity a){ArrayList<Anime> rows=YoruBrain.priorities(18);ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,470)));if(rows.isEmpty())col.addView(Ui.text(a,"Добавьте тайтлы в коллекцию или историю — Tsuyu построит приоритеты автоматически",12,Ui.MUTED,false));else for(Anime anime:rows)animeLine(a,col,anime,YoruBrain.nextHint(anime),true);Ui.custom(a,"Приоритеты просмотра",sc,"Готово",null,"План",()->queue(a),null);}
    static void marathon(Activity a){ArrayList<Anime> rows=YoruBrain.marathon(16);ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,470)));col.addView(Ui.text(a,"Маршрут без лишнего выбора: короткое, начатое, закреплённое и удобное для вечера",12,Ui.MUTED,false));Ui.space(col,12);if(rows.isEmpty())col.addView(Ui.text(a,"Откройте каталог и добавьте пару тайтлов — марафон появится автоматически",12,Ui.MUTED,false));else for(Anime anime:rows)animeLine(a,col,anime,YoruBrain.nextHint(anime),true);Ui.custom(a,"Марафон",sc,"Готово",null,"Случайный",()->{Anime pick=YoruBrain.surprise();if(pick!=null)Ui.openDetails(a,pick);},null);}
    static void taste(Activity a){TextView body=Ui.text(a,YoruBrain.tasteMap(),13,Ui.MUTED,false);body.setLineSpacing(Ui.dp(a,5),1);Ui.custom(a,"Карта вкуса",body,"Готово",null,"Подборки",()->smart(a),null);}
    static void doctor(Activity a,Runnable done){ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,470)));for(String line:YoruBrain.libraryDoctor()){TextView row=Ui.text(a,line,13,line.startsWith("✓")?Ui.EMERALD:Ui.MUTED,true);row.setPadding(Ui.dp(a,12),Ui.dp(a,10),Ui.dp(a,12),Ui.dp(a,10));row.setBackground(Ui.stroke(Ui.CARD,13,a));col.addView(row,Ui.lp(a,-1,-2));Ui.space(col,8);}Ui.space(col,4);ArrayList<Anime> stale=YoruBrain.restartList(8);if(!stale.isEmpty()){col.addView(Ui.text(a,"Вернуться после паузы",16,Ui.TEXT,true));Ui.space(col,8);for(Anime anime:stale)animeLine(a,col,anime,YoruBrain.nextHint(anime),true);}Ui.custom(a,"Диагностика коллекции",sc,"Готово",null,null,null,null);}

    static void smart(Activity a){ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,460)));smartBlock(a,col,"Для вас",YoruBrain.shelf("forYou",5));smartBlock(a,col,"Короткий марафон",YoruBrain.shelf("short",5));smartBlock(a,col,"Фильмы на вечер",YoruBrain.shelf("movies",5));smartBlock(a,col,"Сейчас выходит",YoruBrain.shelf("ongoing",5));smartBlock(a,col,"Классика",YoruBrain.shelf("classics",5));smartBlock(a,col,"Пересмотреть",YoruBrain.shelf("rewatch",5));Ui.custom(a,"Умные подборки",sc,"Готово",null,"Случайный выбор",()->{Anime pick=YoruBrain.surprise();if(pick!=null)Ui.openDetails(a,pick);else Ui.toast(a,"Откройте каталог, чтобы Tsuyu собрал подборку");},null);}
    static void cleanup(Activity a,Runnable done){if(done!=null)done.run();}
    private static void smartBlock(Activity a,LinearLayout col,String title,List<Anime> rows){if(rows==null||rows.isEmpty())return;col.addView(Ui.text(a,title,16,Ui.TEXT,true));Ui.space(col,8);for(Anime anime:rows)animeLine(a,col,anime,YoruBrain.chip(anime),false);Ui.space(col,12);}
    static void stats(Activity a){JSONObject s=YoruApp.app().store.stats();LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);metric(a,col,"Тайтлов в истории",String.valueOf(s.optInt("titles")));metric(a,col,"Серий в истории",String.valueOf(s.optInt("episodes")));metric(a,col,"Завершено",String.valueOf(s.optInt("finished")));metric(a,col,"В коллекции",String.valueOf(s.optInt("favorites")));metric(a,col,"В плане просмотра",String.valueOf(s.optInt("queue")));metric(a,col,"Оценок",String.valueOf(s.optInt("ratings")));metric(a,col,"Пересмотров",String.valueOf(s.optInt("rewatches")));long minutes=Math.max(0,s.optLong("seconds")/60);metric(a,col,"Время просмотра",minutes>=60?minutes/60+" ч "+minutes%60+" мин":minutes+" мин");JSONArray genres=s.optJSONArray("genres");StringBuilder g=new StringBuilder();for(int i=0;genres!=null&&i<genres.length();i++){if(g.length()>0)g.append(", ");g.append(genres.optString(i));}Ui.space(col,8);col.addView(Ui.text(a,g.length()>0?"Частые жанры: "+g:"Жанры появятся после просмотра и добавления в коллекцию",12,Ui.MUTED,false));Ui.custom(a,"Статистика просмотра",col,"Готово",null,null,null,null);}
    private static void animeLine(Activity a,LinearLayout col,Anime anime,String subtitle,boolean play){LinearLayout row=Ui.row(a);row.setPadding(Ui.dp(a,12),Ui.dp(a,10),Ui.dp(a,12),Ui.dp(a,10));row.setBackground(Ui.stroke(Ui.CARD,13,a));LinearLayout words=Ui.column(a);words.addView(Ui.text(a,YoruBrain.title(anime),13,Ui.TEXT,true));if(subtitle!=null&&!subtitle.isEmpty()){Ui.space(words,5);words.addView(Ui.text(a,subtitle,10,Ui.MUTED,false));}row.addView(words,new LinearLayout.LayoutParams(0,-2,1));Ui.Icon icon=new Ui.Icon(a,play?"play":"heart");icon.color=Ui.PURPLE;row.addView(icon,Ui.lp(a,22,22));row.setOnClickListener(v->Ui.openDetails(a,anime));Ui.press(row);col.addView(row,Ui.lp(a,-1,-2));Ui.space(col,7);}
    private static void metric(Activity a,LinearLayout host,String label,String value){LinearLayout row=Ui.row(a);row.setPadding(Ui.dp(a,13),Ui.dp(a,11),Ui.dp(a,13),Ui.dp(a,11));row.setBackground(Ui.stroke(Ui.CARD,13,a));row.addView(Ui.text(a,label,12,Ui.MUTED,false),new LinearLayout.LayoutParams(0,-2,1));row.addView(Ui.text(a,value,15,Ui.PURPLE,true));host.addView(row,Ui.lp(a,-1,-2));Ui.space(host,8);}
}
