package com.tsuyu.line;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.content.pm.ResolveInfo;
import android.media.MediaScannerConnection;
import android.net.Uri;
import android.os.*;
import android.provider.MediaStore;
import androidx.core.content.FileProvider;
import androidx.media3.common.util.*;
import androidx.media3.datasource.*;
import androidx.media3.datasource.cache.*;
import androidx.media3.exoplayer.offline.Download;
import org.json.*;
import java.io.*;
import java.util.*;

@UnstableApi
final class OfflineExporter {
    static final int REQ_SAVE_DOCUMENT=4303;
    private static String pendingDocumentPath,pendingDocumentName;
    private OfflineExporter(){}
    static boolean canExport(Download d){return d!=null&&d.state==Download.STATE_COMPLETED&&singleFile(d);}
    static String format(Download d){if(d==null)return "—";String ext=extension(d);if(ext.equals("mp4")||ext.equals("mkv")||ext.equals("webm")||ext.equals("m4v"))return "Видеофайл";if(ext.equals("m3u8")||ext.equals("mpd"))return "Tsuyu офлайн";return singleFile(d)?"Готовый файл":"Tsuyu офлайн";}
    static void share(Activity a,Download d){export(a,d,"Готовим видео для отправки…",file->{try{Uri u=uri(a,file);Intent intent=new Intent(Intent.ACTION_SEND);intent.setType("video/*");intent.putExtra(Intent.EXTRA_STREAM,u);intent.setClipData(ClipData.newUri(a.getContentResolver(),"video",u));intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);grant(a,intent,u);Intent chooser=Intent.createChooser(intent,"Поделиться серией");chooser.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);chooser.setClipData(ClipData.newUri(a.getContentResolver(),"video",u));a.startActivity(chooser);}catch(Exception e){Ui.toast(a,"Не удалось открыть меню отправки");}});}
    static void saveToMovies(Activity a,Download d){if(Build.VERSION.SDK_INT<29&&a.checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED){a.requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE},4302);Ui.toast(a,"Разрешите сохранение и нажмите ещё раз");return;}export(a,d,"Готовим файл для Видео / Tsuyu…",file->saveFileToMovies(a,file));}
    static void saveWithPicker(Activity a,Download d){export(a,d,"Готовим видео для проводника…",file->{try{pendingDocumentPath=file.getAbsolutePath();pendingDocumentName=file.getName();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(mime(file.getName()));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);i.putExtra(Intent.EXTRA_TITLE,file.getName());a.startActivityForResult(i,REQ_SAVE_DOCUMENT);}catch(Exception e){Ui.toast(a,"Не удалось открыть системный проводник");}});}
    static void finishDocumentSave(Activity a,int code,Intent data){String path=pendingDocumentPath,name=pendingDocumentName;pendingDocumentPath=null;pendingDocumentName=null;if(code!=Activity.RESULT_OK||data==null||data.getData()==null){Ui.toast(a,"Сохранение отменено");return;}if(path==null||path.isEmpty()){Ui.toast(a,"Файл уже не подготовлен");return;}File file=new File(path);Uri target=data.getData();Ui.Progress wait=Ui.progress(a,"Сохраняем через проводник…",false,null);YoruApp.app().io.execute(()->{try(InputStream in=new BufferedInputStream(new FileInputStream(file));OutputStream out=a.getContentResolver().openOutputStream(target)){if(out==null)throw new IOException();long copied=copyBytes(in,out);if(copied<file.length())throw new EOFException();YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Сохранено: "+(name==null?file.getName():name));});}catch(Exception e){YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Не удалось сохранить через проводник");});}});}
    static String details(Download d){JSONObject m=DownloadHub.metadata(d);Anime a=Anime.from(m.optJSONObject("anime")),s=Anime.from(m.optJSONObject("source"));StringBuilder b=new StringBuilder();b.append(a.title).append('\n');b.append("Серия: ").append(Ui.number(m.optDouble("episode",1))).append('\n');String voice=m.optString("voice","");if(!voice.isEmpty())b.append("Озвучка: ").append(voice).append('\n');else b.append("Озвучка: Tsuyu").append('\n');int q=m.optInt("quality",0);b.append("Разрешение: ").append(q>0?q+"p":"Оригинал").append('\n');b.append("Тип: ").append(format(d)).append('\n');b.append("Размер: ").append(Ui.bytes(d.getBytesDownloaded()));if(d.contentLength>0)b.append(" / ").append(Ui.bytes(d.contentLength));b.append('\n').append(singleFile(d)?"Можно открыть в другом приложении, сохранить в Видео или выбрать папку через проводник":"Смотрите эту загрузку во встроенном просмотре Tsuyu");return b.toString();}
    private interface FileAction {void ready(File file);}
    private static void export(Activity a,Download d,String message,FileAction action){if(d==null||d.state!=Download.STATE_COMPLETED){Ui.toast(a,"Серия ещё не скачана полностью");return;}if(!singleFile(d)){Ui.toast(a,"Пересборка видео отключена Эта загрузка открывается только в Tsuyu");return;}copyToCache(a,d,message,action);}
    private static void copyToCache(Activity a,Download d,String message,FileAction action){Ui.Progress wait=Ui.progress(a,message,false,null);YoruApp.app().io.execute(()->{try{File file=cacheFile(a,d);YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();action.ready(file);});}catch(Exception e){YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Не удалось подготовить видеофайл");});}});}
    private static void grant(Context c,Intent intent,Uri u){try{List<ResolveInfo> apps=c.getPackageManager().queryIntentActivities(intent,PackageManager.MATCH_DEFAULT_ONLY);for(ResolveInfo r:apps)if(r.activityInfo!=null)c.grantUriPermission(r.activityInfo.packageName,u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}}
    private static File cacheFile(Context c,Download d)throws Exception{File dir=new File(c.getCacheDir(),"shared-video");if(!dir.exists()&&!dir.mkdirs())throw new IOException();File file=new File(dir,fileName(d));if(validSingle(d,file))return file;if(file.exists())file.delete();try(OutputStream out=new BufferedOutputStream(new FileOutputStream(file))){long bytes=copy(d,out);long expected=expectedBytes(d);if(expected>0&&bytes<tolerated(expected))throw new IOException();}if(!validSingle(d,file))throw new IOException();return file;}
    private static long copy(Download d,OutputStream out)throws Exception{long cached=copySpans(d,out);long expected=expectedBytes(d);if(cached>0){if(expected<=0||cached>=tolerated(expected))return cached;throw new EOFException();}DataSpec.Builder builder=new DataSpec.Builder().setUri(d.request.uri);if(d.request.customCacheKey!=null)builder.setKey(d.request.customCacheKey);DataSource source=YoruApp.app().mediaCache.offlineFactory().createDataSource();byte[] buffer=new byte[256*1024];long total=0;try{source.open(builder.build());int n;while((n=source.read(buffer,0,buffer.length))!=-1){out.write(buffer,0,n);total+=n;}}finally{source.close();}if(expected>0&&total<tolerated(expected))throw new EOFException();return total;}
    private static void saveFileToMovies(Activity a,File file){Ui.Progress wait=Ui.progress(a,"Сохраняем в Видео / Tsuyu…",false,null);YoruApp.app().io.execute(()->{try{String name=file.getName();if(Build.VERSION.SDK_INT>=29){ContentValues values=new ContentValues();values.put(MediaStore.Video.Media.DISPLAY_NAME,name);values.put(MediaStore.Video.Media.MIME_TYPE,mime(name));values.put(MediaStore.Video.Media.RELATIVE_PATH,Environment.DIRECTORY_MOVIES+"/Tsuyu");values.put(MediaStore.Video.Media.IS_PENDING,1);Uri item=a.getContentResolver().insert(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,values);if(item==null)throw new IOException();try(OutputStream out=a.getContentResolver().openOutputStream(item);InputStream in=new BufferedInputStream(new FileInputStream(file))){if(out==null)throw new IOException();long copied=copyBytes(in,out);if(copied<file.length())throw new EOFException();}values.clear();values.put(MediaStore.Video.Media.IS_PENDING,0);a.getContentResolver().update(item,values,null,null);YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Сохранено в Видео / Tsuyu");});}else{File dir=new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_MOVIES),"Tsuyu");if(!dir.exists()&&!dir.mkdirs())throw new IOException();File target=unique(new File(dir,name));try(OutputStream out=new BufferedOutputStream(new FileOutputStream(target));InputStream in=new BufferedInputStream(new FileInputStream(file))){long copied=copyBytes(in,out);if(copied<file.length())throw new EOFException();}MediaScannerConnection.scanFile(a,new String[]{target.getAbsolutePath()},new String[]{mime(target.getName())},null);YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Сохранено в Видео / Tsuyu");});}}catch(Exception e){YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Не удалось сохранить видео");});}});}
    private static long copyBytes(InputStream in,OutputStream out)throws IOException{byte[] b=new byte[256*1024];int n;long total=0;while((n=in.read(b))!=-1){out.write(b,0,n);total+=n;}out.flush();return total;}
    private static Uri uri(Context c,File file){return FileProvider.getUriForFile(c,c.getPackageName()+".files",file);}
    private static boolean singleFile(Download d){String e=extension(d);return e.equals("mp4")||e.equals("mkv")||e.equals("webm")||e.equals("m4v");}
    private static String extension(Download d){try{String p=d.request.uri.getPath();if(p==null)return "";int q=p.lastIndexOf('.');if(q<0)return "";String e=p.substring(q+1).toLowerCase(Locale.ROOT);int cut=e.indexOf('?');return cut>=0?e.substring(0,cut):e;}catch(Exception e){return "";}}
    private static String mime(String name){String n=name.toLowerCase(Locale.ROOT);if(n.endsWith(".mp4")||n.endsWith(".m4v"))return "video/mp4";if(n.endsWith(".webm"))return "video/webm";if(n.endsWith(".mkv"))return "video/x-matroska";return "video/*";}
    private static long copySpans(Download d,OutputStream out)throws IOException{String key=cacheKey(d);NavigableSet<CacheSpan> spans=YoruApp.app().mediaCache.offline().getCachedSpans(key);if(spans==null||spans.isEmpty())return 0;long pos=0,total=0;for(CacheSpan span:spans){if(!span.isCached||span.file==null||!span.file.exists())continue;if(span.position>pos)break;try(InputStream in=new BufferedInputStream(new FileInputStream(span.file))){total+=copyBytes(in,out);}pos=Math.max(pos,span.position+span.length);}return total;}
    private static String cacheKey(Download d){if(d.request.customCacheKey!=null&&!d.request.customCacheKey.isEmpty())return d.request.customCacheKey;return CacheKeyFactory.DEFAULT.buildCacheKey(new DataSpec.Builder().setUri(d.request.uri).build());}
    private static boolean validSingle(Download d,File file){if(file==null||!file.exists()||file.length()<=0)return false;long expected=expectedBytes(d);return expected<=0?file.length()>128*1024:file.length()>=tolerated(expected);}
    private static long expectedBytes(Download d){long a=d.contentLength>0?d.contentLength:0,b=d.getBytesDownloaded();return Math.max(a,b);}
    private static long tolerated(long expected){return Math.max(0,expected-Math.max(8192,expected/100));}
    private static String fileName(Download d){JSONObject m=DownloadHub.metadata(d);Anime a=Anime.from(m.optJSONObject("anime"));String voice=m.optString("voice","");int q=m.optInt("quality",0);String e=extension(d);if(e.isEmpty())e="video";String name=safe(a.title)+" — серия "+Ui.number(m.optDouble("episode",1));if(!voice.isEmpty())name+=" — "+safe(voice);if(q>0)name+=" — "+q+"p";name+=" — "+d.request.id.substring(0,Math.min(8,d.request.id.length()))+"."+e;return name;}
    private static String safe(String s){s=s==null?"":s.replaceAll("[\\\\/:*?\"<>|]+"," ").replaceAll("\\s+"," ").trim();if(s.length()>90)s=s.substring(0,90).trim();return s.isEmpty()?"Tsuyu":s;}
    private static File unique(File file){if(!file.exists())return file;String name=file.getName();int dot=name.lastIndexOf('.');String base=dot<0?name:name.substring(0,dot),ext=dot<0?"":name.substring(dot);for(int i=2;i<1000;i++){File next=new File(file.getParentFile(),base+" ("+i+")"+ext);if(!next.exists())return next;}return file;}
    private static boolean dead(Activity a){return a.isFinishing()||a.isDestroyed();}
}
