package com.tsuyu.line;

import android.app.*;
import android.content.Context;
import android.os.*;
import android.view.*;
import android.webkit.WebView;
import android.widget.*;
import org.json.*;
import java.text.SimpleDateFormat;
import java.util.*;

public final class ProfileScreen extends ScrollView {
    public interface Actions {void run(String action);}
    private final Activity activity;private final LinearLayout body;private TextView mobile,wifi,other,since,cacheSize,offlineSize,free;private long cacheBytes;private final Handler timer=new Handler(Looper.getMainLooper());private boolean attached,refreshing;
    private final Runnable tick=new Runnable(){public void run(){refresh();timer.postDelayed(this,2500);}};
    public ProfileScreen(Activity a,Actions actions){super(a);activity=a;setFillViewport(true);body=Ui.column(a);body.setPadding(Ui.dp(a,18),Ui.dp(a,14),Ui.dp(a,18),Ui.dp(a,30));addView(body);body.addView(Ui.label(a,"Tsuyu"));Ui.space(body,10);body.addView(Ui.text(a,"Настройки",28,Ui.TEXT,true));Ui.space(body,8);body.addView(Ui.text(a,"Просмотр, сеть, загрузки, внешний вид и память",12,Ui.MUTED,false));network(a);stability(a);comfort(a);storage(a);appBlock(a,actions);}

    private void network(Activity a){Ui.space(body,25);body.addView(Ui.text(a,"Сеть",20,Ui.TEXT,true));Ui.space(body,12);LinearLayout stats=Ui.row(a);mobile=stat(stats,"Мобильная");wifi=stat(stats,"Wi‑Fi");body.addView(stats);Ui.space(body,8);other=Ui.text(a,"",11,Ui.MUTED,false);body.addView(other);Ui.space(body,6);since=Ui.text(a,"",10,Ui.MUTED,false);body.addView(since);Ui.space(body,10);body.addView(Ui.button(a,"Сбросить счётчики",false,()->Ui.confirm(a,"Сбросить счётчики?","Начать отсчёт трафика заново? Коллекция и загрузки не изменятся","Сбросить",()->{YoruApp.app().traffic.reset();refresh();},"Отмена")));}
    private void stability(Activity a){Ui.space(body,25);body.addView(Ui.text(a,"Стабильность и загрузки",20,Ui.TEXT,true));Ui.space(body,12);Switch saver=switchRow("Экономия трафика",YoruApp.app().store.dataSaver());body.addView(saver);saver.setOnCheckedChangeListener((b,on)->{YoruApp.app().store.dataSaver(on);YoruApp.app().traffic.preferencesChanged();Ui.toast(a,on?"Экономия включена":"Экономия выключена");});Ui.space(body,8);Switch only=switchRow("Загрузки только по Wi‑Fi",YoruApp.app().store.wifiDownloads());body.addView(only);only.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.wifiDownloads(on);YoruApp.app().downloads().applyRequirements();Ui.toast(a,on?"Загрузки ждут Wi‑Fi":"Мобильная сеть разрешена для загрузок");});}
    private void comfort(Activity a){Ui.space(body,25);body.addView(Ui.text(a,"Комфорт",20,Ui.TEXT,true));Ui.space(body,12);Switch spoiler=switchRow("Без спойлеров",YoruApp.app().store.spoilerSafe());body.addView(spoiler);spoiler.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.smartSetting("spoilerSafe",on);Ui.toast(a,on?"Описания скрываются до нажатия":"Описания снова видны");});Ui.space(body,8);Switch seen=switchRow("Скрывать просмотренное",YoruApp.app().store.hideSeen());body.addView(seen);seen.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.smartSetting("hideSeen",on);Ui.toast(a,on?"Просмотренное скрывается из подборок":"Просмотренное снова видно");});Ui.space(body,8);Switch original=switchRow("Показывать оригинальные названия",YoruApp.app().store.originalTitles());body.addView(original);original.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.smartSetting("originalTitles",on);Ui.toast(a,"Названия обновятся на экранах");});Ui.space(body,8);Switch skip=switchRow("Автопропуск заставки",YoruApp.app().store.autoSkipOpening());body.addView(skip);skip.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.smartSetting("autoSkipOpening",on);Ui.toast(a,on?"Автопропуск включён":"Автопропуск выключен");});}
    private void storage(Activity a){Ui.space(body,25);body.addView(Ui.text(a,"Память",20,Ui.TEXT,true));Ui.space(body,12);LinearLayout card=Ui.column(a);card.setPadding(Ui.dp(a,16),Ui.dp(a,16),Ui.dp(a,16),Ui.dp(a,16));card.setBackground(Ui.stroke(Ui.CARD,13,a));cacheSize=Ui.text(a,"Кэш: …",17,Ui.TEXT,true);card.addView(cacheSize);Ui.space(card,8);offlineSize=Ui.text(a,"Загрузки: …",12,Ui.PURPLE,false);card.addView(offlineSize);Ui.space(card,7);free=Ui.text(a,"",11,Ui.MUTED,false);card.addView(free);Ui.space(card,14);card.addView(Ui.button(a,"Очистить только кэш",false,this::clearCache));Ui.space(card,9);card.addView(Ui.text(a,"Скачанные серии, коллекция и история останутся",10,Ui.MUTED,false));body.addView(card);}
    private void appBlock(Activity a,Actions actions){Ui.space(body,25);body.addView(Ui.text(a,"Приложение",20,Ui.TEXT,true));Ui.space(body,12);for(String[] row:new String[][]{{"playback","Просмотр"},{"appearance","Внешний вид"},{"about","О проекте"}}){body.addView(Ui.button(a,row[1],false,()->actions.run(row[0])));Ui.space(body,9);}body.addView(Ui.text(a,"Tsuyu "+BuildConfig.VERSION_NAME,10,Ui.MUTED,false));}
    private TextView stat(LinearLayout row,String label){LinearLayout c=Ui.column(activity);c.setPadding(Ui.dp(activity,14),Ui.dp(activity,15),Ui.dp(activity,14),Ui.dp(activity,15));c.setBackground(Ui.stroke(Ui.CARD,12,activity));c.addView(Ui.text(activity,label,10,Ui.MUTED,false));Ui.space(c,10);TextView value=Ui.text(activity,"—",20,Ui.PURPLE,true);c.addView(value);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);if(row.getChildCount()>0)p.leftMargin=Ui.dp(activity,9);row.addView(c,p);return value;}
    private Switch switchRow(String label,boolean checked){Switch s=new Switch(activity);s.setText(label);s.setTextColor(Ui.TEXT);s.setTextSize(13);s.setPadding(0,Ui.dp(activity,5),0,Ui.dp(activity,9));s.setChecked(checked);return s;}
    @Override protected void onAttachedToWindow(){super.onAttachedToWindow();attached=true;timer.post(tick);}
    @Override protected void onDetachedFromWindow(){attached=false;timer.removeCallbacksAndMessages(null);super.onDetachedFromWindow();}
    private void refresh(){JSONObject t=YoruApp.app().traffic.snapshot();boolean supported=t.optBoolean("supported",true);mobile.setText(supported?Ui.bytes(t.optLong("mobile")):"Нет данных");wifi.setText(supported?Ui.bytes(t.optLong("wifi")):"Нет данных");other.setText("Другое: "+Ui.bytes(t.optLong("other")));since.setText("С "+new SimpleDateFormat("dd.MM.yyyy HH:mm",new Locale("ru")).format(new Date(t.optLong("since",System.currentTimeMillis()))));if(refreshing)return;refreshing=true;YoruApp.app().io.execute(()->{long tmp=YoruApp.app().mediaCache.temporaryBytes(),download=YoruApp.app().mediaCache.offlineBytes(),remaining=activity.getFilesDir().getUsableSpace();YoruApp.app().main.post(()->{refreshing=false;if(!attached||activity.isFinishing())return;cacheBytes=tmp;cacheSize.setText("Кэш: "+Ui.bytes(tmp));offlineSize.setText("Скачанные серии: "+Ui.bytes(download));free.setText("Свободно: "+Ui.bytes(remaining));});});}
    private void clearCache(){if(YoruApp.app().activePlayers>0){Ui.toast(activity,"Сначала закройте экран просмотра и окно «картинка в картинке»");return;}Ui.confirm(activity,"Очистить "+Ui.bytes(cacheBytes)+" кэша?","Скачанные серии, коллекция и история не будут удалены","Очистить",()->{try{WebView view=new WebView(activity);view.clearCache(true);view.destroy();}catch(Exception ignored){}YoruApp.app().io.execute(()->{YoruApp.app().mediaCache.clearTemporary();YoruApp.app().images.clear();YoruApp.app().api.clearMemory();YoruApp.app().main.post(()->{if(attached){Ui.toast(activity,"Кэш очищен Загрузки сохранены");refresh();}});});},"Отмена");}
}
