package com.tsuyu.line;

import android.content.*;
import android.security.keystore.*;
import android.util.Base64;
import org.json.*;
import java.nio.charset.StandardCharsets;
import java.security.KeyStore;
import javax.crypto.*;
import javax.crypto.spec.GCMParameterSpec;
import java.util.*;

public final class SecureStore {
    private final SharedPreferences prefs;private final CryptoStore crypto=new CryptoStore();private volatile boolean loaded;
    private JSONObject favorites,history,settings;private final HashMap<String,String> favoriteIndex=new HashMap<>(),historyIndex=new HashMap<>();
    public static final String[] BUCKETS={"planned","watching","completed","onhold","dropped"};
    public static final String[] BUCKET_LABELS={"В планах","Смотрю","Просмотрено","Отложено","Брошено"};
    public SecureStore(Context c){prefs=c.getSharedPreferences("private-library",Context.MODE_PRIVATE);favorites=new JSONObject();history=new JSONObject();settings=new JSONObject();}
    private synchronized void ensure(){if(loaded)return;favorites=read("favorites");history=read("history");settings=read("settings");try{if(settings.optInt("mobileDownloadsDefault",0)<1){settings.put("wifiDownloads",false);settings.put("mobileDownloadsDefault",1);write("settings",settings);}}catch(Exception ignored){}rebuildIndexes();loaded=true;}
    public void preload(){ensure();}
    private JSONObject read(String name){return crypto.read(prefs,name);}
    private void write(String name,JSONObject json){crypto.write(prefs,name,json);}
    public boolean ready(){return loaded;}
    public boolean persistent(){ensure();return crypto.hasKey();}
    public synchronized boolean favorite(Anime a){ensure();return !favoriteKey(a).isEmpty();}
    public synchronized String bucket(Anime a){ensure();String key=favoriteKey(a);JSONObject j=key.isEmpty()?null:favorites.optJSONObject(key);return j==null?"":j.optString("bucket","planned");}
    public synchronized void favorite(Anime a,String bucket){ensure();if(!Anime.valid(a))return;try{String key=favoriteKey(a);if(bucket==null||bucket.isEmpty()){if(key.isEmpty())key=a.key();favorites.remove(key);}else{JSONObject old=key.isEmpty()?null:favorites.optJSONObject(key);if(key.isEmpty())key=a.key();int seen=old==null?initialSeen(a):old.optInt("episodesSeen",initialSeen(a));favorites.put(key,new JSONObject().put("release",a.json()).put("bucket",bucket).put("added",old==null?System.currentTimeMillis():old.optLong("added",System.currentTimeMillis())).put("episodesSeen",seen).put("folders",old==null||old.optJSONArray("folders")==null?new JSONArray():old.optJSONArray("folders")));}touchLibrary();write("favorites",favorites);write("settings",settings);rebuildFavoriteIndex();}catch(Exception ignored){}}
    private static int initialSeen(Anime a){int aired=a==null?0:a.aired();if(aired>0)return aired;return a!=null&&"Закончен".equals(a.statusLabel())?Math.max(0,a.episodes):0;}
    private void rebuildIndexes(){rebuildFavoriteIndex();rebuildHistoryIndex();}
    private void rebuildFavoriteIndex(){favoriteIndex.clear();indexRows(favorites,favoriteIndex);}
    private void rebuildHistoryIndex(){historyIndex.clear();indexRows(history,historyIndex);}
    private static void indexRows(JSONObject rows,HashMap<String,String> out){Iterator<String> keys=rows.keys();while(keys.hasNext()){String k=keys.next();JSONObject row=rows.optJSONObject(k);Anime a=row==null?null:Anime.from(row.optJSONObject("release"));out.put(k,k);for(String id:identityKeys(a))if(!out.containsKey(id))out.put(id,k);}}
    private static ArrayList<String> identityKeys(Anime a){ArrayList<String> out=new ArrayList<>();if(!Anime.valid(a))return out;out.add(a.key());if(a.malId>0)out.add(Sec.s("39121943")+a.malId);if(a.anilistId>0)out.add(Sec.s("351d1c43")+a.anilistId);if(a.kpId>0)out.add("kp:"+a.kpId);if(Sec.s("271b1c121c3e0a111b").equals(a.source)&&parsePositive(a.id)>0)out.add(Sec.s("39121943")+parsePositive(a.id));String[] names={a.title,a.original};for(String name:names){String n=ApiRepository.plainName(name);if(n.length()<3)continue;if(a.year>0)out.add("name:"+n+":"+a.year);if(n.length()>7)out.add("name:"+n); }return out;}
    private static int parsePositive(String s){try{int n=Integer.parseInt(s==null?"":s);return n>0?n:0;}catch(Exception e){return 0;}}
    private String indexedKey(Anime a,HashMap<String,String> index){if(!Anime.valid(a))return "";for(String id:identityKeys(a)){String k=index.get(id);if(k!=null&&!k.isEmpty())return k;}return "";}
    private String favoriteKey(Anime a){String k=indexedKey(a,favoriteIndex);if(!k.isEmpty())return k;if(!Anime.valid(a))return "";Iterator<String> keys=favorites.keys();while(keys.hasNext()){String rowKey=keys.next();JSONObject row=favorites.optJSONObject(rowKey);Anime old=row==null?null:Anime.from(row.optJSONObject("release"));if(sameAnime(a,old)){for(String id:identityKeys(a))favoriteIndex.put(id,rowKey);return rowKey;}}return "";}
    private String historyKey(Anime a){String k=indexedKey(a,historyIndex);if(!k.isEmpty())return k;if(!Anime.valid(a))return "";Iterator<String> keys=history.keys();while(keys.hasNext()){String rowKey=keys.next();JSONObject row=history.optJSONObject(rowKey);Anime old=row==null?null:Anime.from(row.optJSONObject("release"));if(sameAnime(a,old)){for(String id:identityKeys(a))historyIndex.put(id,rowKey);return rowKey;}}return "";}
    private static boolean sameAnime(Anime a,Anime b){if(!Anime.valid(a)||!Anime.valid(b))return false;if(a.key().equals(b.key()))return true;if(a.malId>0&&b.malId>0&&a.malId==b.malId)return true;if(a.anilistId>0&&b.anilistId>0&&a.anilistId==b.anilistId)return true;if(a.kpId>0&&b.kpId>0&&a.kpId==b.kpId)return true;String at=ApiRepository.plainName(a.title),ao=ApiRepository.plainName(a.original),bt=ApiRepository.plainName(b.title),bo=ApiRepository.plainName(b.original);boolean name=(!at.isEmpty()&&(at.equals(bt)||at.equals(bo)))||(!ao.isEmpty()&&(ao.equals(bt)||ao.equals(bo)));boolean year=a.year==0||b.year==0||Math.abs(a.year-b.year)<=1;return name&&year;}
    public synchronized List<Anime> favorites(){ensure();return favorites("","");}
    public synchronized List<Anime> favorites(String bucket,String query){ensure();ArrayList<Anime> result=new ArrayList<>();Iterator<String> keys=favorites.keys();String q=query==null?"":query.toLowerCase(Locale.ROOT),folder="";if(bucket!=null&&bucket.startsWith("folder:"))folder=bucket.substring(7);while(keys.hasNext()){JSONObject j=favorites.optJSONObject(keys.next());if(j==null)continue;Anime a=Anime.from(j.optJSONObject("release"));if(!Anime.valid(a))continue;if(!folder.isEmpty()){if(!hasFolder(j,folder))continue;}else if(bucket!=null&&!bucket.isEmpty()&&!bucket.equals(j.optString("bucket","planned")))continue;if(!(a.title+" "+a.original).toLowerCase(Locale.ROOT).contains(q))continue;result.add(a);}result.sort((a,b)->{int p=Boolean.compare(pinned(b),pinned(a));return p!=0?p:a.title.compareToIgnoreCase(b.title);});return result;}
    public synchronized long libraryVersion(){ensure();return favorites.length()*31L+settings.optLong("libraryVersion",0);}
    private void touchLibrary(){try{settings.put("libraryVersion",System.currentTimeMillis());}catch(Exception ignored){}}
    private static String cleanFolder(String value){String v=value==null?"":value.trim().replaceAll("\\s+"," ");v=v.replaceAll("[\\r\\n\\t]"," ");if(v.length()>32)v=v.substring(0,32).trim();return v;}
    private static boolean sameFolder(String a,String b){return cleanFolder(a).equalsIgnoreCase(cleanFolder(b));}
    private static boolean hasFolder(JSONObject item,String folder){JSONArray arr=item==null?null:item.optJSONArray("folders");for(int i=0;arr!=null&&i<arr.length();i++)if(sameFolder(arr.optString(i),folder))return true;return false;}
    public synchronized ArrayList<String> libraryFolders(){ensure();LinkedHashSet<String> set=new LinkedHashSet<>();JSONArray saved=settings.optJSONArray("libraryFolders");for(int i=0;saved!=null&&i<saved.length();i++){String f=cleanFolder(saved.optString(i));if(!f.isEmpty())set.add(f);}Iterator<String> keys=favorites.keys();while(keys.hasNext()){JSONObject item=favorites.optJSONObject(keys.next());JSONArray arr=item==null?null:item.optJSONArray("folders");for(int i=0;arr!=null&&i<arr.length();i++){String f=cleanFolder(arr.optString(i));if(!f.isEmpty())set.add(f);}}return new ArrayList<>(set);}
    public synchronized ArrayList<String> folders(Anime a){ensure();ArrayList<String> out=new ArrayList<>();String key=favoriteKey(a);JSONObject item=key.isEmpty()?null:favorites.optJSONObject(key);JSONArray arr=item==null?null:item.optJSONArray("folders");for(int i=0;arr!=null&&i<arr.length();i++){String f=cleanFolder(arr.optString(i));if(!f.isEmpty()&&!containsFolder(out,f))out.add(f);}return out;}
    public synchronized String folderSummary(Anime a){ArrayList<String> rows=folders(a);if(rows.isEmpty())return "";StringBuilder b=new StringBuilder();for(int i=0;i<rows.size()&&i<3;i++){if(b.length()>0)b.append(", ");b.append(rows.get(i));}if(rows.size()>3)b.append(" +").append(rows.size()-3);return b.toString();}
    public synchronized void favoriteFolders(Anime a,Collection<String> selected){ensure();if(!Anime.valid(a))return;try{String key=favoriteKey(a);JSONObject item=key.isEmpty()?null:favorites.optJSONObject(key);if(item==null){favorite(a,"planned");key=favoriteKey(a);item=key.isEmpty()?null:favorites.optJSONObject(key);}if(item==null)return;JSONArray arr=new JSONArray();ArrayList<String> all=libraryFolders();if(selected!=null)for(String raw:selected){String f=cleanFolder(raw);if(f.isEmpty()||containsFolder(all,f)){}else all.add(f);if(!f.isEmpty()&&!containsFolder(jsonToList(arr),f)&&arr.length()<12)arr.put(f);}item.put("folders",arr);JSONArray saved=new JSONArray();for(String f:all)if(!f.isEmpty()&&saved.length()<40)saved.put(f);settings.put("libraryFolders",saved);touchLibrary();write("favorites",favorites);write("settings",settings);rebuildFavoriteIndex();}catch(Exception ignored){}}
    private static boolean containsFolder(Collection<String> rows,String value){for(String row:rows)if(sameFolder(row,value))return true;return false;}
    private static ArrayList<String> jsonToList(JSONArray arr){ArrayList<String> out=new ArrayList<>();for(int i=0;arr!=null&&i<arr.length();i++){String f=cleanFolder(arr.optString(i));if(!f.isEmpty())out.add(f);}return out;}
    public synchronized boolean updateFavoriteEpisodes(Anime a,int episodes){ensure();String key=favoriteKey(a);if(!Anime.valid(a)||key.isEmpty())return false;try{JSONObject item=favorites.optJSONObject(key);if(item==null)return false;Anime copy=Anime.from(a.json());int released=Math.max(0,episodes),seen=item.optInt("episodesSeen",0);boolean ongoing=copy.ongoing()||copy.episodes>released;boolean repaired=false;if(ongoing&&released>0&&seen>released){seen=released;repaired=true;}boolean alert=seen>0&&released>seen;if(released>seen||seen<=0||repaired){copy.episodes=Math.max(released,copy.episodes);copy.episodesAired=Math.max(copy.episodesAired,copy.episodes>0?Math.min(copy.episodes,released):released);item.put("release",copy.json());item.put("episodesSeen",repaired?released:Math.max(released,seen));write("favorites",favorites);rebuildFavoriteIndex();}return alert;}catch(Exception e){return false;}}
    public synchronized int favoriteCount(){ensure();return favorites.length();}
    public synchronized JSONObject progress(Anime a){ensure();String key=historyKey(a);JSONObject j=key.isEmpty()?null:history.optJSONObject(key);return j==null?new JSONObject():j;}
    public synchronized void progress(Anime a,double episode,int seconds,int duration,String mode,String dubbing,boolean tracked){ensure();if(!Anime.valid(a)||episode<0||!Double.isFinite(episode)||privateMode())return;try{String hKey=historyKey(a);if(hKey.isEmpty())hKey=a.key();JSONObject j=new JSONObject().put("release",a.json()).put("episode",episode).put("time",Math.max(0,seconds)).put("duration",Math.max(0,duration)).put("updated",System.currentTimeMillis()).put("tracked",tracked).put("playerMode",mode==null?"":mode).put("dubbing",dubbing==null?"":dubbing);history.put(hKey,j);if(a.episodes>0&&episode>=a.episodes&&!"ongoing".equalsIgnoreCase(a.status)){removeWatch(a);String favKey=favoriteKey(a);JSONObject fav=favKey.isEmpty()?null:favorites.optJSONObject(favKey);if(fav!=null)fav.put("bucket","completed");}if(history.length()>100){String oldest=null;long at=Long.MAX_VALUE;Iterator<String> keys=history.keys();while(keys.hasNext()){String k=keys.next();long t=history.optJSONObject(k).optLong("updated");if(t<at){oldest=k;at=t;}}if(oldest!=null)history.remove(oldest);}write("favorites",favorites);write("history",history);write("settings",settings);try{if(YoruApp.app()!=null&&YoruApp.app().cache!=null)YoruApp.app().cache.progressMirror(hKey,j);}catch(Exception ignored){}rebuildFavoriteIndex();rebuildHistoryIndex();}catch(Exception ignored){}}
    public synchronized List<Anime> recent(){ensure();ArrayList<JSONObject> values=new ArrayList<>();Iterator<String> keys=history.keys();while(keys.hasNext()){JSONObject x=history.optJSONObject(keys.next());if(x!=null)values.add(x);}values.sort((a,b)->Long.compare(b.optLong("updated"),a.optLong("updated")));ArrayList<Anime> out=new ArrayList<>();for(JSONObject j:values){Anime a=Anime.from(j.optJSONObject("release"));if(Anime.valid(a))out.add(a);}return out;}
    public synchronized void clearHistory(){ensure();history=new JSONObject();write("history",history);rebuildHistoryIndex();}
    public synchronized int quality(){ensure();return QualityPlus.clamp(settings.optInt("quality",720));}
    public synchronized boolean autoNext(){ensure();return settings.optBoolean("autoNext",true);}
    public synchronized void settings(int quality,boolean next){ensure();try{settings.put("quality",QualityPlus.clamp(quality)).put("autoNext",next);write("settings",settings);}catch(Exception ignored){}}
    public synchronized int fontScale(){ensure();return Math.max(85,Math.min(130,settings.optInt("fontScale",100)));}
    public synchronized boolean customFont(){ensure();return settings.optBoolean("customFont",false);}
    public synchronized String fontName(){ensure();return settings.optString("fontName","Системный");}
    public synchronized void appearance(int scale,boolean custom,String name){ensure();try{settings.put("fontScale",Math.max(85,Math.min(130,scale))).put("customFont",custom).put("fontName",name==null||name.trim().isEmpty()?"Свой шрифт":name.trim());write("settings",settings);}catch(Exception ignored){}}
    public synchronized boolean liteMode(){ensure();return settings.optBoolean("liteMode",false);}
    public synchronized void liteMode(boolean enabled){ensure();try{settings.put("liteMode",enabled);write("settings",settings);}catch(Exception ignored){}}
    public synchronized boolean directOnly(){return true;}
    public synchronized void directOnly(boolean enabled){ensure();try{settings.put("directOnly",enabled);write("settings",settings);}catch(Exception ignored){}}
    public synchronized float playbackSpeed(){ensure();double v=settings.optDouble("playbackSpeed",1.0);if(v<0.75||v>2.0)v=1.0;return (float)v;}
    public synchronized void playbackSpeed(float speed){ensure();try{float v=Math.max(0.75f,Math.min(2.0f,speed));settings.put("playbackSpeed",v);write("settings",settings);}catch(Exception ignored){}}
    public synchronized boolean takeUpdatePulse(){ensure();try{long now=System.currentTimeMillis(),last=settings.optLong("lastUpdatePulse",0);if(now-last<3*60*1000L)return false;settings.put("lastUpdatePulse",now);write("settings",settings);return true;}catch(Exception e){return false;}}
    public synchronized void updateCheckState(long at,int checked,int alerts,String status){ensure();try{settings.put("lastEpisodeCheckAt",Math.max(0,at));settings.put("lastEpisodeCheckCount",Math.max(0,checked));settings.put("lastEpisodeCheckAlerts",Math.max(0,alerts));settings.put("lastEpisodeCheckStatus",status==null?"":status);write("settings",settings);}catch(Exception ignored){}}
    public synchronized long lastEpisodeCheckAt(){ensure();return settings.optLong("lastEpisodeCheckAt",0);}
    public synchronized int lastEpisodeCheckCount(){ensure();return settings.optInt("lastEpisodeCheckCount",0);}
    public synchronized int lastEpisodeCheckAlerts(){ensure();return settings.optInt("lastEpisodeCheckAlerts",0);}
    public synchronized String lastEpisodeCheckStatus(){ensure();return settings.optString("lastEpisodeCheckStatus","");}
    public synchronized String voicePreference(){ensure();return settings.optString("voicePreference","");}
    public synchronized void voicePreference(String value){ensure();try{String v=value==null?"":value.trim();settings.put("voicePreference",v);if(v.isEmpty())settings.put("onlyPreferredVoice",false);else rememberVoiceLocked(v);write("settings",settings);}catch(Exception ignored){}}
    public synchronized boolean onlyPreferredVoice(){ensure();return settings.optBoolean("onlyPreferredVoice",false)&&!ApiRepository.voiceKey(voicePreference()).isEmpty();}
    public synchronized void onlyPreferredVoice(boolean value){ensure();try{settings.put("onlyPreferredVoice",value&&!ApiRepository.voiceKey(voicePreference()).isEmpty());write("settings",settings);}catch(Exception ignored){}}
    public synchronized String voiceFor(Anime a){ensure();try{JSONObject map=settings.optJSONObject("voiceByAnime");if(map==null||a==null)return "";String v=map.optString(voiceAnimeKey(a),"");if(v.isEmpty())v=map.optString(voiceAnimeAltKey(a),"");return v==null?"":v;}catch(Exception e){return "";}}
    public synchronized void setVoiceFor(Anime a,String value){ensure();if(a==null)return;try{JSONObject map=settings.optJSONObject("voiceByAnime");if(map==null)map=new JSONObject();String v=value==null?"":value.trim();String key=voiceAnimeKey(a);if(key.isEmpty())return;String alt=voiceAnimeAltKey(a);if(v.isEmpty()){map.remove(key);if(!alt.isEmpty())map.remove(alt);}else{if(map.length()>=60){java.util.Iterator<String> keys=map.keys();if(keys.hasNext())map.remove(keys.next());}map.put(key,v);if(!alt.isEmpty()&&!alt.equals(key))map.put(alt,v);}settings.put("voiceByAnime",map);write("settings",settings);}catch(Exception ignored){}}
    private static String voiceAnimeKey(Anime a){if(a==null)return "";if(a.malId>0)return Sec.s("39121943")+a.malId;try{String k=a.key();return k==null?"":k;}catch(Exception e){return "";}}private static String voiceAnimeAltKey(Anime a){if(a==null||a.malId<=0)return "";try{String k=a.key();return k==null?"":k;}catch(Exception e){return "";}}
    public synchronized int todayStamp(){java.util.Calendar c=java.util.Calendar.getInstance();return c.get(java.util.Calendar.YEAR)*10000+(c.get(java.util.Calendar.MONTH)+1)*100+c.get(java.util.Calendar.DAY_OF_MONTH);}
    public synchronized Anime dailyHero(){ensure();try{JSONObject saved=settings.optJSONObject("dailyHero");if(saved==null||saved.optInt("day",-1)!=todayStamp())return null;Anime a=Anime.from(saved.optJSONObject("anime"));return Anime.valid(a)?a:null;}catch(Exception e){return null;}}
    public synchronized void saveDailyHero(Anime a){ensure();if(a==null||!Anime.valid(a))return;try{JSONObject saved=new JSONObject();saved.put("day",todayStamp());saved.put("anime",a.json());settings.put("dailyHero",saved);write("settings",settings);}catch(Exception ignored){}}
    public synchronized int downloadResolution(){ensure();return QualityPlus.clamp(settings.optInt("quality",720));}
    public synchronized void downloadResolution(int value){ensure();try{settings.put("quality",QualityPlus.clamp(value));write("settings",settings);}catch(Exception ignored){}}
    public synchronized ArrayList<String> favoriteVoices(){ensure();LinkedHashMap<String,String> map=new LinkedHashMap<>();String current=settings.optString("voicePreference","");String ck=ApiRepository.voiceKey(current);if(!ck.isEmpty())map.put(ck,ApiRepository.voiceTitle(current));JSONArray arr=settings.optJSONArray("favoriteVoices");for(int i=0;arr!=null&&i<arr.length();i++){String v=arr.optString(i,"");String title=ApiRepository.voiceTitle(v);String key=ApiRepository.voiceKey(title.isEmpty()?v:title);if(!key.isEmpty()&&!map.containsKey(key))map.put(key,title.isEmpty()?v:title);}return new ArrayList<>(map.values());}
    public synchronized void rememberVoice(String value){ensure();try{rememberVoiceLocked(value);write("settings",settings);}catch(Exception ignored){}}
    private void rememberVoiceLocked(String value)throws JSONException{if(value!=null&&value.startsWith("src:"))return;String title=ApiRepository.voiceTitle(value);if(title.isEmpty())title=value==null?"":value.trim();String key=ApiRepository.voiceKey(title);if(key.isEmpty())return;ArrayList<String> next=new ArrayList<>();next.add(title);JSONArray old=settings.optJSONArray("favoriteVoices");for(int i=0;old!=null&&i<old.length()&&next.size()<12;i++){String v=old.optString(i,"");String vk=ApiRepository.voiceKey(v);if(vk.isEmpty()||vk.equals(key))continue;next.add(ApiRepository.voiceTitle(v).isEmpty()?v:ApiRepository.voiceTitle(v));}JSONArray arr=new JSONArray();for(String v:next)arr.put(v);settings.put("favoriteVoices",arr);}
    public synchronized int voicePriority(String actual){ensure();String text=actual==null?"":actual;ArrayList<String> fav=favoriteVoices();for(int i=0;i<fav.size();i++)if(ApiRepository.voiceMatches(fav.get(i),text))return i;return -1;}
    public synchronized String favoriteVoiceSummary(){ArrayList<String> fav=favoriteVoices();if(fav.isEmpty())return "Авто";StringBuilder b=new StringBuilder();for(int i=0;i<fav.size()&&i<3;i++){if(b.length()>0)b.append(" → ");b.append(ApiRepository.voiceTitle(fav.get(i)));}if(fav.size()>3)b.append(" +").append(fav.size()-3);return b.toString();}
    public synchronized boolean privateMode(){ensure();return settings.optBoolean("privateMode",false);}
    public synchronized boolean spoilerSafe(){ensure();return settings.optBoolean("spoilerSafe",false);}
    public synchronized boolean hideSeen(){ensure();return settings.optBoolean("hideSeen",false);}
    public synchronized boolean autoSkipOpening(){ensure();return settings.optBoolean("autoSkipOpening",false);}
    public synchronized int sleepTimer(){ensure();return Math.max(0,Math.min(180,settings.optInt("sleepTimer",0)));}
    public synchronized boolean originalTitles(){ensure();return settings.optBoolean("originalTitles",false);}
    public synchronized void smartSetting(String key,boolean value){ensure();try{settings.put(key,value);write("settings",settings);}catch(Exception ignored){}}
    public synchronized void sleepTimer(int minutes){ensure();try{settings.put("sleepTimer",Math.max(0,Math.min(180,minutes)));write("settings",settings);}catch(Exception ignored){}}
    public synchronized int rating(Anime a){ensure();return Anime.valid(a)?Math.max(0,Math.min(10,settings.optInt("rating:"+a.key(),0))):0;}
    public synchronized void rating(Anime a,int value){ensure();if(!Anime.valid(a))return;try{String key="rating:"+a.key();value=Math.max(0,Math.min(10,value));if(value==0)settings.remove(key);else settings.put(key,value);write("settings",settings);}catch(Exception ignored){}}
    public synchronized String tags(Anime a){ensure();return Anime.valid(a)?settings.optString("tags:"+a.key(),""):"";}
    public synchronized void tags(Anime a,String value){ensure();if(!Anime.valid(a))return;try{String key="tags:"+a.key();String v=value==null?"":value.trim().replaceAll("\\s*,\\s*",", ");if(v.length()>160)v=v.substring(0,160).trim();if(v.isEmpty())settings.remove(key);else settings.put(key,v);write("settings",settings);}catch(Exception ignored){}}
    public synchronized boolean hidden(Anime a){ensure();return Anime.valid(a)&&settings.optBoolean("hidden:"+a.key(),false);}
    public synchronized void hidden(Anime a,boolean hide){ensure();if(!Anime.valid(a))return;try{String key="hidden:"+a.key();if(hide)settings.put(key,true);else settings.remove(key);write("settings",settings);}catch(Exception ignored){}}
    public synchronized boolean pinned(Anime a){ensure();return Anime.valid(a)&&settings.optBoolean("pin:"+a.key(),false);}
    public synchronized void pinned(Anime a,boolean pin){ensure();if(!Anime.valid(a))return;try{String key="pin:"+a.key();if(pin)settings.put(key,true);else settings.remove(key);write("settings",settings);}catch(Exception ignored){}}
    public synchronized void clearHidden(){ensure();clearPrefixed("hidden:");}
    public synchronized void clearPrefixed(String prefix){ensure();try{ArrayList<String> keys=new ArrayList<>();Iterator<String> it=settings.keys();while(it.hasNext()){String k=it.next();if(k.startsWith(prefix))keys.add(k);}for(String k:keys)settings.remove(k);write("settings",settings);}catch(Exception ignored){}}
    public synchronized int rewatch(Anime a){ensure();return Anime.valid(a)?Math.max(0,settings.optInt("rewatch:"+a.key(),0)):0;}
    public synchronized void addRewatch(Anime a){ensure();if(!Anime.valid(a))return;try{settings.put("rewatch:"+a.key(),rewatch(a)+1);write("settings",settings);}catch(Exception ignored){}}
    public synchronized String note(Anime a){ensure();return Anime.valid(a)?settings.optString("note:"+a.key(),""):"";}
    public synchronized void note(Anime a,String text){ensure();if(!Anime.valid(a))return;try{String key="note:"+a.key();String v=text==null?"":text.trim();if(v.isEmpty())settings.remove(key);else settings.put(key,v.length()>800?v.substring(0,800):v);write("settings",settings);}catch(Exception ignored){}}
    public synchronized void enqueueWatch(Anime a){ensure();if(!Anime.valid(a))return;try{JSONArray old=settings.optJSONArray("watchQueue"),next=new JSONArray();next.put(a.json());for(int i=0;old!=null&&i<old.length()&&next.length()<30;i++){Anime row=Anime.from(old.optJSONObject(i));if(Anime.valid(row)&&!row.key().equals(a.key()))next.put(row.json());}settings.put("watchQueue",next);write("settings",settings);}catch(Exception ignored){}}
    public synchronized void removeWatch(Anime a){ensure();if(!Anime.valid(a))return;try{JSONArray old=settings.optJSONArray("watchQueue"),next=new JSONArray();for(int i=0;old!=null&&i<old.length();i++){Anime row=Anime.from(old.optJSONObject(i));if(Anime.valid(row)&&!row.key().equals(a.key()))next.put(row.json());}settings.put("watchQueue",next);write("settings",settings);}catch(Exception ignored){}}
    public synchronized void clearWatchQueue(){ensure();try{settings.remove("watchQueue");write("settings",settings);}catch(Exception ignored){}}
    public synchronized List<Anime> watchQueue(){ensure();ArrayList<Anime> out=new ArrayList<>();JSONArray rows=settings.optJSONArray("watchQueue");for(int i=0;rows!=null&&i<rows.length();i++){Anime a=Anime.from(rows.optJSONObject(i));if(Anime.valid(a))out.add(a);}return out;}
    public synchronized JSONObject stats(){ensure();try{JSONObject out=new JSONObject();int titles=0,episodes=0,finished=0;long seconds=0;HashMap<String,Integer> genres=new HashMap<>();Iterator<String> keys=history.keys();while(keys.hasNext()){JSONObject h=history.optJSONObject(keys.next());if(h==null)continue;Anime a=Anime.from(h.optJSONObject("release"));if(!Anime.valid(a))continue;titles++;episodes+=Math.max(1,(int)Math.floor(h.optDouble("episode",1)));seconds+=Math.max(0,h.optInt("time",0));if(a.episodes>0&&h.optDouble("episode",0)>=a.episodes)finished++;for(String g:a.genres)if(g!=null&&!g.trim().isEmpty())genres.put(g,genres.getOrDefault(g,0)+1);}ArrayList<Map.Entry<String,Integer>> gs=new ArrayList<>(genres.entrySet());gs.sort((a,b)->b.getValue()-a.getValue());JSONArray top=new JSONArray();for(int i=0;i<Math.min(5,gs.size());i++)top.put(gs.get(i).getKey());return out.put("titles",titles).put("episodes",episodes).put("seconds",seconds).put("finished",finished).put("favorites",favorites.length()).put("queue",watchQueue().size()).put("genres",top).put("ratings",ratedCount()).put("pins",pinnedCount()).put("hidden",hiddenCount()).put("rewatches",rewatchCount());}catch(Exception e){return new JSONObject();}}

    public synchronized int todayEpisodes(){ensure();Calendar c=Calendar.getInstance();c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);long start=c.getTimeInMillis();int n=0;Iterator<String> keys=history.keys();while(keys.hasNext()){JSONObject h=history.optJSONObject(keys.next());if(h!=null&&h.optLong("updated")>=start)n++;}return n;}
    public synchronized int ratedCount(){ensure();int n=0;Iterator<String> keys=settings.keys();while(keys.hasNext())if(keys.next().startsWith("rating:"))n++;return n;}
    public synchronized int pinnedCount(){ensure();int n=0;Iterator<String> keys=settings.keys();while(keys.hasNext())if(keys.next().startsWith("pin:"))n++;return n;}
    public synchronized int hiddenCount(){ensure();int n=0;Iterator<String> keys=settings.keys();while(keys.hasNext())if(keys.next().startsWith("hidden:"))n++;return n;}
    public synchronized int rewatchCount(){ensure();int n=0;Iterator<String> keys=settings.keys();while(keys.hasNext()){String k=keys.next();if(k.startsWith("rewatch:"))n+=Math.max(0,settings.optInt(k,0));}return n;}
    public synchronized String calendarCache(){ensure();return settings.optString("calendarCache","");}
    public synchronized void calendarCache(JSONArray rows){ensure();try{settings.put("calendarCache",rows==null?"":rows.toString());settings.put("calendarCacheAt",System.currentTimeMillis());write("settings",settings);}catch(Exception ignored){}}
    public synchronized long calendarCacheAt(){ensure();return settings.optLong("calendarCacheAt",0);}
    public synchronized String sourceProfile(){ensure();return settings.optString("sourceProfile","");}
    public synchronized void sourceProfile(String json){ensure();try{if(json==null||json.length()<20)settings.remove("sourceProfile");else settings.put("sourceProfile",json);settings.put("sourceProfileAt",System.currentTimeMillis());write("settings",settings);}catch(Exception ignored){}}
    public synchronized long sourceProfileAt(){ensure();return settings.optLong("sourceProfileAt",0);}

    public synchronized JSONObject sourceSnapshot(){ensure();try{JSONObject raw=settings.optJSONObject("sourceStats");return raw==null?new JSONObject():new JSONObject(raw.toString());}catch(Exception e){return new JSONObject();}}
    public synchronized void sourceEvent(String source,boolean ok,long ms,int episodes,int variants,int quality){ensure();String id=source==null||source.trim().isEmpty()?"yoru":source.trim();try{JSONObject all=settings.optJSONObject("sourceStats");if(all==null)all=new JSONObject();JSONObject row=all.optJSONObject(id);if(row==null)row=new JSONObject();row.put(ok?"ok":"fail",row.optInt(ok?"ok":"fail",0)+1);row.put("failRun",ok?0:Math.min(20,row.optInt("failRun",0)+1));row.put("last",System.currentTimeMillis());if(ok)row.put("lastOk",System.currentTimeMillis());else row.put("lastBad",System.currentTimeMillis());if(ms>0){long avg=row.optLong("avg",0);row.put("avg",avg<=0?ms:(avg*3+ms)/4);}if(episodes>0)row.put("episodes",Math.max(row.optInt("episodes",0),Math.min(episodes,10000)));if(variants>0)row.put("variants",Math.max(row.optInt("variants",0),Math.min(variants,10000)));if(quality>0)row.put("quality",Math.max(row.optInt("quality",0),Math.min(quality,4320)));all.put(id,row);ArrayList<String> keys=new ArrayList<>();Iterator<String> it=all.keys();while(it.hasNext())keys.add(it.next());if(keys.size()>36){final JSONObject stats=all;keys.sort((a,b)->Long.compare(stats.optJSONObject(a)==null?0:stats.optJSONObject(a).optLong("last",0),stats.optJSONObject(b)==null?0:stats.optJSONObject(b).optLong("last",0)));for(int i=0;i<keys.size()-36;i++)all.remove(keys.get(i));}settings.put("sourceStats",all);write("settings",settings);}catch(Exception ignored){}}
    public synchronized void replaceWatchQueue(List<Anime> rows){ensure();try{JSONArray next=new JSONArray();LinkedHashSet<String> seen=new LinkedHashSet<>();if(rows!=null)for(Anime a:rows){if(!Anime.valid(a)||!seen.add(a.key()))continue;next.put(a.json());if(next.length()>=30)break;}if(next.length()==0)settings.remove("watchQueue");else settings.put("watchQueue",next);write("settings",settings);}catch(Exception ignored){}}
    public synchronized ArrayList<Anime> mood(String mood){ensure();ArrayList<Anime> source=new ArrayList<>(favorites());source.addAll(recent());LinkedHashMap<String,Anime> out=new LinkedHashMap<>();String m=mood==null?"":mood.toLowerCase(Locale.ROOT);for(Anime a:source){String text=(a.title+" "+a.original+" "+a.type+" "+String.join(" ",a.genres)).toLowerCase(Locale.ROOT);boolean ok=m.contains("уют")&&(text.contains("повсед")||text.contains("роман")||text.contains("комед"))||m.contains("экшен")&&(text.contains("экшен")||text.contains("приключ"))||m.contains("корот")&&(a.episodes>0&&a.episodes<=13||text.contains("фильм"))||m.contains("роман")&&text.contains("роман");if(ok)out.put(a.key(),a);}return new ArrayList<>(out.values());}

    public synchronized String exportData(){ensure();try{return new JSONObject().put("format","yoru.android.v5").put("exportedAt",new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX",Locale.ROOT).format(new Date())).put("favorites",favorites).put("history",history).put("settings",settings).toString(2);}catch(Exception e){return "{}";}}
    public synchronized int importData(String input) throws Exception {ensure();if(input.length()>5*1024*1024)throw new Exception("Файл слишком большой");JSONObject root=new JSONObject(input);if(!root.optString("format").matches("yoru(?:\\.v[1-5]|\\.android\\.v[12345])"))throw new Exception("Выберите файл коллекции Tsuyu");int count=0;for(String name:new String[]{"favorites","history"}){JSONObject data=root.optJSONObject(name);if(data==null)continue;Iterator<String> keys=data.keys();while(keys.hasNext()){String k=keys.next();JSONObject item=data.optJSONObject(k);if(item==null)continue;Anime a=Anime.from(item.optJSONObject("release"));if(!Anime.valid(a)||!k.equals(a.key()))continue;if(name.equals("favorites")){String bucket=item.optString("bucket","planned");if(!Arrays.asList(BUCKETS).contains(bucket))bucket="planned";favorites.put(k,new JSONObject().put("release",a.json()).put("bucket",bucket).put("added",System.currentTimeMillis()).put("episodesSeen",Math.max(0,item.optInt("episodesSeen",a.episodes))).put("folders",item.optJSONArray("folders")==null?new JSONArray():item.optJSONArray("folders")));}else{double ep=item.optDouble("episode",1);if(!Double.isFinite(ep)||ep<0||ep>100000)continue;history.put(k,new JSONObject().put("release",a.json()).put("episode",ep).put("time",Math.min(100000,Math.max(0,item.optInt("time")))).put("duration",Math.min(100000,Math.max(0,item.optInt("duration")))).put("tracked",item.optBoolean("tracked",true)).put("updated",System.currentTimeMillis()).put("playerMode",item.optString("playerMode","")).put("dubbing",item.optString("dubbing","")));}count++;if(count>5000)break;}}JSONObject imported=root.optJSONObject("settings");if(imported!=null){HashSet<String> exact=new HashSet<>(Arrays.asList("fontScale","customFont","fontName","quality","playbackSpeed","autoNext","dataSaver","wifiDownloads","directOnly","liteMode","privateMode","spoilerSafe","hideSeen","autoSkipOpening","sleepTimer","originalTitles","watchQueue","sourceStats","voicePreference","onlyPreferredVoice","favoriteVoices","libraryFolders","libraryVersion","mobileDownloadsDefault"));Iterator<String> sk=imported.keys();while(sk.hasNext()){String key=sk.next();if(exact.contains(key)||key.startsWith("note:")||key.startsWith("rating:")||key.startsWith("tags:")||key.startsWith("pin:")||key.startsWith("hidden:")||key.startsWith("rewatch:"))settings.put(key,imported.opt(key));}}write("favorites",favorites);write("history",history);write("settings",settings);return count;}
    public synchronized JSONObject traffic(){ensure();return read("traffic");}
    public synchronized void traffic(JSONObject value){ensure();write("traffic",value);}
    public synchronized boolean dataSaver(){ensure();return settings.optBoolean("dataSaver",false);}
    public synchronized boolean wifiDownloads(){ensure();return settings.optBoolean("wifiDownloads",false);}
    public synchronized void dataSaver(boolean enabled){ensure();try{settings.put("dataSaver",enabled);write("settings",settings);}catch(Exception ignored){}}
    public synchronized void wifiDownloads(boolean enabled){ensure();try{settings.put("wifiDownloads",enabled);write("settings",settings);}catch(Exception ignored){}}

    public synchronized List<String> searchHistory(){ensure();ArrayList<String> out=new ArrayList<>();JSONArray rows=settings.optJSONArray("searchHistory");for(int i=0;rows!=null&&i<rows.length();i++){String q=rows.optString(i,"").trim();if(!q.isEmpty()&&!out.contains(q))out.add(q);if(out.size()>=14)break;}return out;}
    public synchronized void addSearch(String query){ensure();String q=query==null?"":query.trim().replaceAll("\\s+"," ");if(q.length()<2)return;if(q.length()>80)q=q.substring(0,80).trim();try{ArrayList<String> rows=new ArrayList<>();rows.add(q);for(String old:searchHistory())if(!old.equalsIgnoreCase(q))rows.add(old);JSONArray arr=new JSONArray();for(int i=0;i<Math.min(14,rows.size());i++)arr.put(rows.get(i));settings.put("searchHistory",arr);write("settings",settings);}catch(Exception ignored){}}
    public synchronized void clearSearchHistory(){ensure();try{settings.remove("searchHistory");write("settings",settings);}catch(Exception ignored){}}

}
