package com.tsuyu.line;

import android.net.Uri;
import android.util.Base64;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.regex.*;

final class VideoResolver {
    private static final int SHIFT=18;
    private static final String CHROME="Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Mobile Safari/537.36";
    private VideoResolver(){}
    static TreeMap<Integer,String> resolve(ApiRepository api,String input)throws Exception{
        String url=ApiRepository.embed(input);if(url.isEmpty())url=ApiRepository.safeUrl(input);if(url.isEmpty())throw new IOException("Просмотр не передал данные");
        TreeMap<Integer,String> direct=direct(api,url);if(!direct.isEmpty())return direct;String host=host(url);String path=path(url);
        if(has(host,"yummyani.me","yani.tv")&&path.toLowerCase(Locale.ROOT).contains("iframecvh"))return cvh(api,url);
        if(has(host,"cdnvideohub.com","plapi.cdnvideohub.com"))return cvh(api,url);
        if(has(host,"animetka.com")&&path.toLowerCase(Locale.ROOT).startsWith("/api/anime/playlist"))return animetkaPlaylist(api,url);
        if(has(host,"kodikplayer.com","kodik.info","kodik.cc","kodik.biz","aniqit.com"))return kodik(api,url);
        if(has(host,"alloha.yani.tv","alloha.tv"))return alloha(api,url);
        if(has(host,"aksor.tv","aksor.yani.tv","player.aksor.tv"))return aksor(api,url);
        if(has(host,"video.sibnet.ru","sibnet.ru"))return sibnet(api,url);
        if(has(host,"stormo.tv"))return stormo(api,url);
        if(host.contains("ladony")||path.toLowerCase(Locale.ROOT).contains("vid.php"))return hlsEndpoint(api,url,"https://online.anidub.com/");
        if(has(host,"vk.com","vkvideo.ru","vkvideo.com")||path.toLowerCase(Locale.ROOT).contains("iframevk"))return vk(api,url);
        if(has(host,"rutube.ru"))return rutube(api,url);
        if(has(host,"zedfilm.ru","hlamer.ru"))return zedfilm(api,url);
        if(has(host,"aniboom.one"))return aniboom(api,url);
        if(has(host,"video1.anilib.me","video2.anilib.me","anilib.me"))return anilib(url);
        TreeMap<Integer,String> probed=probeUrl(url,"https://yani.tv/");if(!probed.isEmpty())return probed;
        return scan(api,url);
    }
    static TreeMap<Integer,String> probe(ApiRepository api,String input){try{String url=ApiRepository.safeUrl(input);if(url.isEmpty())return new TreeMap<>();TreeMap<Integer,String> direct=direct(api,url);if(!direct.isEmpty())return direct;return probeUrl(url,"https://yani.tv/");}catch(Exception e){return new TreeMap<>();}}
    static boolean downloadable(String url){String safe=ApiRepository.safeUrl(url);if(safe.isEmpty())return false;String lower=safe.toLowerCase(Locale.ROOT);String path=Uri.parse(safe).getPath();String p=path==null?lower:path.toLowerCase(Locale.ROOT);return p.contains(".m3u8")||p.contains(".mpd")||p.contains(".mp4")||p.contains(".mkv")||p.contains(".webm")||lower.contains(".m3u8")||lower.contains(".mpd")||lower.contains(".mp4")||lower.contains(".mkv")||lower.contains(".webm")||lower.contains("hls")||lower.contains("playlist")||lower.contains("manifest");}
    static int qualityOf(String url){return quality(url);}
    private static boolean has(String host,String...names){for(String n:names)if(host.equals(n)||host.endsWith("."+n))return true;return false;}
    private static String host(String url){try{String h=Uri.parse(url).getHost();return h==null?"":h.toLowerCase(Locale.ROOT);}catch(Exception e){return "";}}
    private static String path(String url){try{String p=Uri.parse(url).getPath();return p==null?"":p;}catch(Exception e){return "";}}
    private static TreeMap<Integer,String> direct(ApiRepository api,String url)throws Exception{TreeMap<Integer,String> out=new TreeMap<>();String lower=url.toLowerCase(Locale.ROOT);String p=path(url).toLowerCase(Locale.ROOT);if(p.contains(".m3u8")||lower.contains(".m3u8")){try{out.putAll(hls(api,url));}catch(Exception ignored){}if(out.isEmpty())out.put(quality(url),url);}else if(p.contains(".mpd")||lower.contains(".mpd")){try{out.putAll(dash(api,url));}catch(Exception ignored){}if(out.isEmpty())out.put(0,url);}else if(p.contains(".mp4")||p.contains(".mkv")||p.contains(".webm")||lower.contains(".mp4")||lower.contains(".mkv")||lower.contains(".webm")){out.put(quality(url),url);}return clean(out);}
    private static TreeMap<Integer,String> hls(ApiRepository api,String url)throws Exception{return parseHls(api.document(url),url);}
    private static TreeMap<Integer,String> hlsWithHeaders(ApiRepository api,String url,String referer)throws Exception{return parseHls(api.request(url,"GET",null,false,headers(origin(url),referer)),url);}
    private static TreeMap<Integer,String> parseHls(String manifest,String url){TreeMap<Integer,String> out=new TreeMap<>();if(manifest==null||!manifest.trim().startsWith("#EXTM3U"))return out;String[] lines=manifest.split("\\r?\\n");int height=0;for(String line:lines){String l=line.trim();if(l.startsWith("#EXT-X-STREAM-INF")){Matcher m=Pattern.compile("RESOLUTION=\\d+x(\\d+)").matcher(l);height=m.find()?Integer.parseInt(m.group(1)):0;}else if(!l.isEmpty()&&!l.startsWith("#")&&height>0){out.put(height,absolute(url,l));height=0;}}return clean(out);}
    private static TreeMap<Integer,String> directWithReferer(ApiRepository api,String url,String referer)throws Exception{TreeMap<Integer,String> out=new TreeMap<>();String lower=url.toLowerCase(Locale.ROOT),p=path(url).toLowerCase(Locale.ROOT);if(p.contains(".m3u8")||lower.contains(".m3u8")){try{out.putAll(hlsWithHeaders(api,url,referer));}catch(Exception ignored){}if(out.isEmpty())out.put(quality(url),url);}else if(p.contains(".mpd")||lower.contains(".mpd")){try{out.putAll(dash(api,url));}catch(Exception ignored){}if(out.isEmpty())out.put(0,url);}else if(p.contains(".mp4")||p.contains(".mkv")||p.contains(".webm")||lower.contains(".mp4")||lower.contains(".mkv")||lower.contains(".webm")){out.put(quality(url),url);}return clean(out);}
    private static TreeMap<Integer,String> dash(ApiRepository api,String url)throws Exception{TreeMap<Integer,String> out=new TreeMap<>();String mpd=api.document(url);Matcher m=Pattern.compile("height=\\\"(\\d+)\\\"").matcher(mpd);while(m.find())out.put(Integer.parseInt(m.group(1)),url);return clean(out);}
    private static TreeMap<Integer,String> kodik(ApiRepository api,String url)throws Exception{Page page=fetch(url,"https://yani.tv/");String html=page.text.replace("\n","").replace("\r","");LinkedHashMap<String,String> payload=new LinkedHashMap<>();String urlParams=find(html,"\\burlParams\\s*=\\s*'([^']+)' ");if(urlParams.isEmpty())urlParams=find(html,"\\burlParams\\s*=\\s*'([^']+)'");if(urlParams.isEmpty())urlParams=find(html,"\\burlParams\\s*=\\s*\"([^\"]+)\"");if(!urlParams.isEmpty()){JSONObject params=new JSONObject(unescape(urlParams));payload.put("d",params.optString("d"));payload.put("d_sign",params.optString("d_sign"));payload.put("pd",params.optString("pd"));payload.put("pd_sign",params.optString("pd_sign"));payload.put("ref",params.optString("ref"));payload.put("ref_sign",params.optString("ref_sign"));}else{payload.put("d",find(html,"var\\s+domain\\s*=\\s*[\"'](.+?)[\"']"));payload.put("d_sign",find(html,"var\\s+d_sign\\s*=\\s*[\"'](.+?)[\"']"));payload.put("pd",find(html,"var\\s+pd\\s*=\\s*[\"'](.+?)[\"']"));payload.put("pd_sign",find(html,"var\\s+pd_sign\\s*=\\s*[\"'](.+?)[\"']"));payload.put("ref",find(html,"var\\s+ref\\s*=\\s*[\"'](.+?)[\"']"));payload.put("ref_sign",find(html,"var\\s+ref_sign\\s*=\\s*[\"'](.+?)[\"']"));}
        payload.put("type",first(find(html,"(?:videoInfo|vInfo)\\.type\\s*\\+?=\\s*[\"'](.+?)[\"']"),find(html,"[\"']type[\"']\\s*:\\s*[\"'](.+?)[\"']")));
        payload.put("hash",first(find(html,"(?:videoInfo|vInfo)\\.hash\\s*\\+?=\\s*[\"'](.+?)[\"']"),find(html,"[\"']hash[\"']\\s*:\\s*[\"'](.+?)[\"']")));
        payload.put("id",first(first(find(html,"(?:videoInfo|vInfo)\\.id\\s*\\+?=\\s*[\"'](.+?)[\"']"),find(html,"[\"']id[\"']\\s*:\\s*[\"'](.+?)[\"']")),find(html,"var\\s+videoId\\s*=\\s*[\"'](\\d+)[\"']")));
        String endpoint=origin(url)+"/ftor";String script=find(html,"src=\\\"((?://[^\\\"]+)?/assets/js/app\\.player_single[^\\\"]+)\\\"");if(script.isEmpty())script=find(html,"src=['\"]([^'\"]*app\\.player_single[^'\"]+)['\"]");if(!script.isEmpty())try{String scriptUrl=absolute(url,script);String body=fetch(scriptUrl,url).text;String path=endpointPath(body);if(!path.isEmpty())endpoint=origin(scriptUrl)+path;}catch(Exception ignored){}
        for(Map.Entry<String,String> e:payload.entrySet())if(e.getValue()==null||e.getValue().isEmpty())throw new IOException("Просмотр не передал данные");StringBuilder body=new StringBuilder();add(body,"d",payload.get("d"),false);add(body,"d_sign",payload.get("d_sign"),false);add(body,"pd",payload.get("pd"),false);add(body,"pd_sign",payload.get("pd_sign"),false);add(body,"ref",payload.get("ref"),looksEncoded(payload.get("ref")));add(body,"ref_sign",payload.get("ref_sign"),false);add(body,"bad_user","true",false);add(body,"cdn_is_working","true",false);add(body,"type",payload.get("type"),false);add(body,"hash",payload.get("hash"),false);add(body,"id",payload.get("id"),false);add(body,"info","{}",false);
        JSONObject root;try{root=new JSONObject(post(endpoint,body.toString(),url,page.cookies));}catch(Exception first){JSONObject json=new JSONObject();json.put("videoId",payload.get("id"));for(Map.Entry<String,String> e:payload.entrySet())json.put(e.getKey(),e.getValue());root=new JSONObject(postJson(endpoint,json.toString(),url,page.cookies));}JSONObject links=root.optJSONObject("links");TreeMap<Integer,String> out=new TreeMap<>();if(links!=null){int[] order={240,360,480,720,1080,1440,2160,4320};for(int q:order)putKodik(out,links,String.valueOf(q),q);Iterator<String> keys=links.keys();while(keys.hasNext()){String key=keys.next();try{putKodik(out,links,key,Integer.parseInt(key.replaceAll("\\D+","")));}catch(Exception ignored){putKodik(out,links,key,0);}}}if(out.isEmpty())throw new IOException("Просмотр не открыл подходящий вариант");return clean(out);}
    private static void putKodik(TreeMap<Integer,String> out,JSONObject links,String key,int q){JSONArray arr=links.optJSONArray(key);if(arr==null||arr.length()==0)return;JSONObject row=arr.optJSONObject(0);if(row==null)return;String src=row.optString("src","");try{String decoded=fixProtocol(decode(src));String safe=ApiRepository.safeUrl(decoded);if(!safe.isEmpty())out.put(q>0?q:quality(safe),safe);}catch(Exception ignored){}}
    private static TreeMap<Integer,String> cvh(ApiRepository api,String url)throws Exception{Uri uri=Uri.parse(url.startsWith("//")?"https:"+url:url);String animeId=uri.getQueryParameter("anime_id");if(animeId==null||animeId.isEmpty())animeId=uri.getQueryParameter("id");String episode=uri.getQueryParameter("episode");String dubbing=uri.getQueryParameter("dubbing_code");if(animeId==null||animeId.isEmpty())throw new IOException("Просмотр не передал данные");int ep=1;try{if(episode!=null)ep=Integer.parseInt(episode);}catch(Exception ignored){}HashMap<String,String> h=headers("https://ru.yummyani.me","https://ru.yummyani.me/");h.put("Accept","application/json");JSONObject playlist=new JSONObject(api.request("https://plapi.cdnvideohub.com/api/v1/player/sv/playlist?pub=745&id="+enc(animeId)+"&aggr=mali","GET",null,false,h));JSONArray items=playlist.optJSONArray("items");JSONObject chosen=null;for(int i=0;items!=null&&i<items.length();i++){JSONObject item=items.optJSONObject(i);if(item==null||item.optInt("episode",-1)!=ep)continue;if(chosen==null)chosen=item;if(dubbing!=null&&!dubbing.isEmpty()&&item.optString("voiceStudio").equalsIgnoreCase(dubbing)){chosen=item;break;}}if(chosen==null)throw new IOException("Просмотр не нашёл серию");String vk=chosen.optString("vkId","");if(vk.isEmpty())throw new IOException("Просмотр не передал видео");JSONObject video=new JSONObject(api.request("https://plapi.cdnvideohub.com/api/v1/player/sv/video/"+enc(vk),"GET",null,false,h));String failover=video.optString("failoverHost","");JSONObject sources=video.optJSONObject("sources");TreeMap<Integer,String> out=new TreeMap<>();if(sources!=null){putCvh(out,240,sources.optString("mpegLowestUrl"),failover);putCvh(out,360,sources.optString("mpegLowUrl"),failover);putCvh(out,480,sources.optString("mpegMediumUrl"),failover);putCvh(out,720,sources.optString("mpegHighUrl"),failover);putCvh(out,1080,sources.optString("mpegFullHdUrl"),failover);putCvh(out,1440,first(sources.optString("mpegQuadHdUrl"),sources.optString("mpeg2kUrl")),failover);putCvh(out,2160,first(sources.optString("mpegUltraHdUrl"),first(sources.optString("mpegUhdUrl"),first(sources.optString("mpeg4kUrl"),first(sources.optString("mpeg2060Url"),sources.optString("mpegOriginalUrl"))))),failover);Iterator<String> keys=sources.keys();while(keys.hasNext()){String key=keys.next();String value=sources.optString(key,"");String lower=key.toLowerCase(Locale.ROOT)+" "+value.toLowerCase(Locale.ROOT);int q=lower.contains("4k")||lower.contains("uhd")?2160:quality(lower);if(q>=1200)putCvh(out,q,value,failover);}}if(out.isEmpty())throw new IOException("Просмотр не подготовил вариант");return clean(out);}
    private static void putCvh(TreeMap<Integer,String> out,int q,String value,String failover){String safe=ApiRepository.safeUrl(normalizeCvh(value,failover));if(!safe.isEmpty())out.put(q>0?q:quality(safe),safe);}
    private static String normalizeCvh(String value,String failover){String safe=ApiRepository.safeUrl(value);if(safe.isEmpty()||failover==null||failover.isEmpty())return safe;try{URL u=new URL(safe);if(!u.getProtocol().equalsIgnoreCase("https")||!u.getHost().matches("\\d{1,3}(?:\\.\\d{1,3}){3}"))return safe;return new URL(u.getProtocol(),failover,u.getPort(),u.getFile()).toString();}catch(Exception e){return safe;}}
    private static TreeMap<Integer,String> alloha(ApiRepository api,String url)throws Exception{String page=api.request(url,"GET",null,false,headers(origin(url),"https://yani.tv/"));String id=find(page,"const\\s+fileList\\s+=\\s*JSON\\.parse\\('\\{\\\"type\\\":\\s*\\\"serial\\\",\\s*\\\"active\\\":\\s*\\{\\\"id\\\":\\s*(\\d+)");if(id.isEmpty())id=find(page,"\\\"active\\\"\\s*:\\s*\\{\\s*\\\"id\\\"\\s*:\\s*(\\d+)");String token=find(page,"const\\s+userParam\\s*=\\s*\\{[\\s\\S]*?token:\\s*[\"'](.+?)[\"']");String user=find(page,"<meta\\s+name\\s*=\\s*[\"']user[\"']\\s+content\\s*=\\s*[\"'](.+?)[\"']");if(id.isEmpty()||token.isEmpty()||user.isEmpty())throw new IOException("Alloha не передал параметры");HashMap<String,String> h=headers("https://alloha.yani.tv",url);h.put("Accepts-Controls",user);String json=api.request("https://alloha.yani.tv/movie/"+id,"POST","token="+enc(token)+"&av1=true&autoplay=0&audio=&subtitle=",true,h);JSONObject root=new JSONObject(json);JSONArray sources=root.optJSONArray("hlsSource");TreeMap<Integer,String> out=new TreeMap<>();JSONObject first=sources==null||sources.length()==0?null:sources.optJSONObject(0);JSONObject q=first==null?null:first.optJSONObject("quality");if(q!=null){Iterator<String> keys=q.keys();while(keys.hasNext()){String key=keys.next();if(key.equalsIgnoreCase("Object"))continue;String link=q.optString(key,"");int cut=link.indexOf(" or ");if(cut>=0)link=link.substring(0,cut);String safe=ApiRepository.safeUrl(link);if(!safe.isEmpty())try{out.put(Integer.parseInt(key),safe);}catch(Exception ignored){out.put(quality(safe),safe);}}}if(out.isEmpty())throw new IOException("Alloha не открыл подходящий вариант");return clean(out);}
    private static TreeMap<Integer,String> aksor(ApiRepository api,String url)throws Exception{String origin=origin(url);TreeMap<Integer,String> out=new TreeMap<>();try{String id=Uri.parse(url).getLastPathSegment();if(id!=null&&!id.isEmpty()){JSONObject j=new JSONObject(api.request(origin+"/api/video/"+enc(id),"GET",null,false,headers(origin,url)));JSONObject q=j.optJSONObject("qualities");if(q!=null){Iterator<String> keys=q.keys();while(keys.hasNext()){String key=keys.next();String safe=ApiRepository.safeUrl(q.optString(key));if(!safe.isEmpty())out.put(Integer.parseInt(key.replaceAll("\\D+","")),safe);}}JSONArray arr=j.optJSONArray("sources");for(int i=0;arr!=null&&i<arr.length();i++){JSONObject row=arr.optJSONObject(i);if(row==null)continue;String safe=ApiRepository.safeUrl(row.optString("url",row.optString("src","")));if(!safe.isEmpty())out.put(row.optInt("height",quality(safe)),safe);}}}catch(Exception ignored){}if(!out.isEmpty())return clean(out);String page=api.request(url,"GET",null,false,headers(origin,"https://yani.tv/"));String link=find(page,"var\\s+videoUrl\\s*=\\s*[\"'](.+?)[\"']");String safe=absolute(url,link);if(!safe.isEmpty())out.put(quality(safe),safe);return clean(out);}
    private static TreeMap<Integer,String> sibnet(ApiRepository api,String url)throws Exception{String page=api.request(url,"GET",null,false,headers(origin(url),url));TreeMap<Integer,String> out=new TreeMap<>();Matcher hls=Pattern.compile("[\"'](/v/[a-z0-9]+/[^\"']+?\\.m3u8)[\"']",Pattern.CASE_INSENSITIVE).matcher(page);while(hls.find()){String safe=ApiRepository.safeUrl("https://video.sibnet.ru"+hls.group(1));if(!safe.isEmpty())out.put(quality(safe)>0?quality(safe):480,safe);}Matcher mp4=Pattern.compile("src:\\s*[\"']/(.+?\\.mp4[^\"']*)[\"']",Pattern.CASE_INSENSITIVE).matcher(page);while(mp4.find()){String safe=ApiRepository.safeUrl("https://video.sibnet.ru/"+mp4.group(1).replace("\\/","/"));if(!safe.isEmpty())out.put(quality(safe)>0?quality(safe):480,safe);}if(out.isEmpty())throw new IOException("Sibnet не вернул видео");return clean(out);}
    private static TreeMap<Integer,String> stormo(ApiRepository api,String url)throws Exception{String page=api.request(url,"GET",null,false,headers(origin(url),url));TreeMap<Integer,String> out=new TreeMap<>();Matcher m=Pattern.compile("https?:\\\\?/\\\\?/www\\.stormo\\.tv/get_file/[^\"'<>\\s]+?\\.mp4/?",Pattern.CASE_INSENSITIVE).matcher(page);while(m.find()){String safe=ApiRepository.safeUrl(m.group().replace("\\/","/"));if(!safe.isEmpty())out.put(quality(safe),safe);}if(out.isEmpty())return scan(api,url);return clean(out);}
    private static TreeMap<Integer,String> hlsEndpoint(ApiRepository api,String url,String referer)throws Exception{String body=api.request(url,"GET",null,false,headers(origin(url),referer));TreeMap<Integer,String> out=new TreeMap<>();if(body.trim().startsWith("#EXTM3U")){out.put(quality(url),url);return clean(out);}return scan(api,url);}
    private static TreeMap<Integer,String> vk(ApiRepository api,String url)throws Exception{String page=normalizePayload(api.request(url,"GET",null,false,headers(origin(url),"https://yani.tv/")));String ext=find(page,"(?:src|href)=[\\\"']([^\\\"']*video_ext\\.php[^\\\"']+)[\\\"']");if(ext.isEmpty())ext=find(page,"(https?:\\\\?/\\\\?/vk\\.com/video_ext\\.php[^\\\"'<>\\s]+)");if(!ext.isEmpty())try{String extUrl=absolute(url,ext);page+="\n"+normalizePayload(api.request(extUrl,"GET",null,false,headers("https://vk.com",url)));}catch(Exception ignored){}TreeMap<Integer,String> out=new TreeMap<>();Matcher escaped=Pattern.compile("\\\\\"(?:url|mp4_)(\\d{3,4})\\\\\"\\s*:\\s*\\\\\"(.+?)\\\\\"",Pattern.CASE_INSENSITIVE).matcher(page);while(escaped.find())addStream(api,out,url,escaped.group(2),url,parseInt(escaped.group(1)));Matcher named=Pattern.compile("[\\\"'](?:url|mp4_)(\\d{3,4})[\\\"']\\s*[:=]\\s*[\\\"']([^\\\"']+)[\\\"']",Pattern.CASE_INSENSITIVE).matcher(page);while(named.find())addStream(api,out,url,named.group(2),url,parseInt(named.group(1)));Matcher hls=Pattern.compile("[\\\"'](?:hls_fmp4|hls|url)[\\\"']\\s*[:=]\\s*[\\\"']([^\\\"']+)[\\\"']",Pattern.CASE_INSENSITIVE).matcher(page);while(hls.find())addStream(api,out,url,hls.group(1),url,0);collectStreams(api,out,url,page,url);if(out.isEmpty())throw new IOException("VK не вернул видео");return clean(out);}
    private static TreeMap<Integer,String> rutube(ApiRepository api,String url)throws Exception{String id=rutubeId(url);if(id.isEmpty())try{id=rutubeId(api.request(url,"GET",null,false,headers("https://rutube.ru","https://rutube.ru/")));}catch(Exception ignored){}if(id.isEmpty())throw new IOException("Просмотр не передал данные");HashMap<String,String> h=headers("https://rutube.ru",url);h.put("Accept","application/json,*/*");JSONObject root=new JSONObject(api.request("https://rutube.ru/api/play/options/"+enc(id)+"/?no_404=true&referer="+enc(url)+"&pver=v2","GET",null,false,h));JSONObject balancer=root.optJSONObject("video_balancer");String stream="";if(balancer!=null)stream=first(balancer.optString("m3u8"),first(balancer.optString("default"),first(balancer.optString("hls"),balancer.optString("url"))));TreeMap<Integer,String> out=new TreeMap<>();if(!stream.isEmpty())addStream(api,out,url,stream,url,0);if(out.isEmpty())collectStreams(api,out,url,root.toString(),url);if(out.isEmpty())throw new IOException("Просмотр не подготовил вариант");return clean(out);}
    private static String rutubeId(String text){Matcher p=Pattern.compile("(?i)(?:video|play/embed)/([a-f0-9]{32}|\\d{5,12})").matcher(text==null?"":text);if(p.find())return p.group(1);Matcher any=Pattern.compile("(?i)\\b([a-f0-9]{32})\\b").matcher(text==null?"":text);return any.find()?any.group(1):"";}
    private static TreeMap<Integer,String> zedfilm(ApiRepository api,String url)throws Exception{String page=normalizePayload(api.request(url,"GET",null,false,headers("https://hlamer.ru","https://yani.tv/")));TreeMap<Integer,String> out=new TreeMap<>();String encoded=find(page,"video_Init\\(\\s*[\\\"']([^\\\"']+)[\\\"']");if(!encoded.isEmpty())try{JSONObject json=new JSONObject(new String(Base64.decode(encoded,Base64.DEFAULT),StandardCharsets.UTF_8));for(String key:new String[]{"url","url2","hls","dash","src","file","source"})addStream(api,out,url,json.optString(key),url,0);Iterator<String> keys=json.keys();while(keys.hasNext()){String key=keys.next();Object value=json.opt(key);String lower=key.toLowerCase(Locale.ROOT);if(value instanceof String&&(lower.contains("url")||lower.contains("hls")||lower.contains("dash")||lower.contains("file")))addStream(api,out,url,(String)value,url,0);}}catch(Exception ignored){}collectStreams(api,out,url,page,url);if(out.isEmpty())return scan(api,url);return clean(out);}
    private static TreeMap<Integer,String> aniboom(ApiRepository api,String url)throws Exception{String page=api.request(url,"GET",null,false,headers(origin(url),"https://yani.tv/"));String dash=find(page,"&quot;dash&quot;:&quot;\\{\\\\&quot;src\\\\&quot;:\\\\&quot;(https[^;]+?\\.mpd)");if(dash.isEmpty())dash=find(page,"\\\"dash\\\"\\s*:\\s*\\\"(https[^\\\"]+?\\.mpd)\\\"");dash=dash.replace("\\\\\\/","/").replace("\\/","/");String safe=ApiRepository.safeUrl(dash);if(safe.isEmpty())throw new IOException("Aniboom не вернул видео");TreeMap<Integer,String> out=dash(api,safe);if(out.isEmpty())out.put(0,safe);return clean(out);}

    private static TreeMap<Integer,String> animetkaPlaylist(ApiRepository api,String url)throws Exception{String json=api.request(url,"GET",null,false,headers("https://animetka.com","https://animetka.com/"));JSONObject root=new JSONObject(json);TreeMap<Integer,String> out=new TreeMap<>();int want=queryInt(url,"episode",0);JSONArray list=root.optJSONArray("list");for(int i=0;list!=null&&i<list.length();i++){JSONObject item=list.optJSONObject(i);if(item==null)continue;double n=animetkaListNumber(item,i+1);if(want>0&&list.length()>1&&Math.abs(n-want)>0.001)continue;String file=normalizePayload(item.optString("file",""));Matcher m=Pattern.compile("[[]([0-9]{3,4})]([^,]+)").matcher(file);while(m.find()){int q=parseInt(m.group(1));String stream=absolute("https://animetka.com/",m.group(2));if(!stream.isEmpty())addStream(api,out,"https://animetka.com/",stream,url,q);}if(out.isEmpty()){Matcher raw=Pattern.compile("([^,]+?(?:[.]m3u8|[.]mpd|[.]mp4)[^,]*)",Pattern.CASE_INSENSITIVE).matcher(file);while(raw.find())addStream(api,out,"https://animetka.com/",raw.group(1),url,quality(raw.group(1)));}}if(out.isEmpty()){String link=ApiRepository.embed(root.optString("link",""));if(!link.isEmpty())try{return resolve(api,link);}catch(Exception ignored){}}return clean(out);}
    private static int queryInt(String url,String key,int fallback){try{String v=Uri.parse(url).getQueryParameter(key);return v==null||v.isEmpty()?fallback:Integer.parseInt(v.replaceAll("[^0-9]",""));}catch(Exception e){return fallback;}}
    private static double numberIn(String text,double fallback){Matcher m=Pattern.compile("[0-9]+(?:[.][0-9]+)?").matcher(text==null?"":text);try{return m.find()?Double.parseDouble(m.group()):fallback;}catch(Exception e){return fallback;}}
    private static double animetkaListNumber(JSONObject item,int fallback){String id=item.optString("id","");Matcher s=Pattern.compile("s([0-9]+(?:[.][0-9]+)?)",Pattern.CASE_INSENSITIVE).matcher(id);if(s.find())try{return Double.parseDouble(s.group(1));}catch(Exception ignored){}return numberIn(item.optString("title",""),fallback);}

    private static TreeMap<Integer,String> anilib(String url)throws Exception{String safe=ApiRepository.safeUrl(url);TreeMap<Integer,String> out=new TreeMap<>();if(!safe.isEmpty())out.put(quality(safe),safe);return clean(out);}
    private static void collectStreams(ApiRepository api,TreeMap<Integer,String> out,String base,String page,String referer){String text=normalizePayload(page);collectObjects(api,out,base,text,referer);Matcher field=Pattern.compile("(?:file|src|source|url|hls|dash)\\s*[:=]\\s*[\\\"']([^\\\"']+?(?:\\.m3u8|\\.mpd|\\.mp4|playlist|manifest|hls)[^\\\"']*)[\\\"']",Pattern.CASE_INSENSITIVE).matcher(text);while(field.find())addStream(api,out,base,field.group(1),referer,0);Matcher full=Pattern.compile("https?:\\\\?/\\\\?/[^\\\"'<>\\s]+?(?:\\.m3u8|\\.mpd|\\.mp4|playlist|manifest|hls)[^\\\"'<>\\s]*",Pattern.CASE_INSENSITIVE).matcher(text);while(full.find())addStream(api,out,base,full.group(),referer,0);Matcher proto=Pattern.compile("//[^\\\"'<>\\s]+?(?:\\.m3u8|\\.mpd|\\.mp4|playlist|manifest|hls)[^\\\"'<>\\s]*",Pattern.CASE_INSENSITIVE).matcher(text);while(proto.find())addStream(api,out,base,proto.group(),referer,0);}
    private static void collectObjects(ApiRepository api,TreeMap<Integer,String> out,String base,String text,String referer){Matcher obj=Pattern.compile("\\{[^{}]{0,1200}(?:file|src|source|url|hls|dash)[^{}]{0,1200}\\}",Pattern.CASE_INSENSITIVE).matcher(text);while(obj.find()){String row=obj.group();String link=first(find(row,"(?:file|src|source|url|hls|dash)\\s*[:=]\\s*[\\\"']([^\\\"']+?(?:\\.m3u8|\\.mpd|\\.mp4|playlist|manifest|hls)[^\\\"']*)[\\\"']"),find(row,"[\\\"']([^\\\"']+?(?:\\.m3u8|\\.mpd|\\.mp4|playlist|manifest|hls)[^\\\"']*)[\\\"']"));String q=first(find(row,"(?:quality|label|height|res)\\s*[:=]\\s*[\\\"']?([1-9][0-9]{2,3})p?"),find(row,"([1-9][0-9]{2,3})p"));addStream(api,out,base,link,referer,parseInt(q));}}
    private static void addStream(ApiRepository api,TreeMap<Integer,String> out,String base,String raw,String referer,int forcedQuality){String safe=absolute(base,normalizePayload(raw));if(!streamLike(safe))return;try{TreeMap<Integer,String> found=directWithReferer(api,safe,referer);if(found.isEmpty())found=probeUrl(safe,referer);if(found.isEmpty())out.put(forcedQuality>0?forcedQuality:quality(safe),safe);else for(Map.Entry<Integer,String> e:found.entrySet())if(!out.containsValue(e.getValue()))out.put(e.getKey()>0?e.getKey():(forcedQuality>0?forcedQuality:quality(e.getValue())),e.getValue());}catch(Exception e){out.put(forcedQuality>0?forcedQuality:quality(safe),safe);}}
    private static boolean streamLike(String url){String l=url==null?"":url.toLowerCase(Locale.ROOT);if(l.isEmpty()||l.contains("doubleclick")||l.contains("/ads/")||l.contains("yandex")||l.contains("adfox")||l.contains("ima"))return false;return l.contains(".m3u8")||l.contains(".mpd")||l.contains(".mp4")||l.contains(".mkv")||l.contains(".webm")||l.contains("playlist")||l.contains("manifest")||l.contains("/hls/");}
    private static String normalizePayload(String s){return s==null?"":s.replace("\\\\/","/").replace("\\/","/").replace("&amp;","&").replace("\\u0026","&").trim();}
    private static TreeMap<Integer,String> scan(ApiRepository api,String url)throws Exception{String page=api.request(url,"GET",null,false,headers(origin(url),"https://yani.tv/"));TreeMap<Integer,String> direct=new TreeMap<>();collectStreams(api,direct,url,page,url);if(!direct.isEmpty())return clean(direct);for(String frame:frames(url,page)){if(frame.equals(url))continue;try{TreeMap<Integer,String> out=resolve(api,frame);if(!out.isEmpty())return clean(out);}catch(Exception ignored){}}ArrayList<String> found=new ArrayList<>();Matcher f=Pattern.compile("(?:file|src|hls|dash|url)\\s*[:=]\\s*[\"']([^\"']+?(?:\\.m3u8|\\.mpd|\\.mp4|playlist|manifest|hls)[^\"']*)[\"']",Pattern.CASE_INSENSITIVE).matcher(page);while(f.find())found.add(f.group(1));Matcher u=Pattern.compile("https?:\\\\?/\\\\?/[^\"'<>\\s]+?(?:\\.m3u8|\\.mpd|\\.mp4|playlist|manifest|hls)[^\"'<>\\s]*",Pattern.CASE_INSENSITIVE).matcher(page);while(u.find())found.add(u.group());for(String s:found){String safe=absolute(url,s.replace("\\/","/"));if(safe.isEmpty())continue;try{TreeMap<Integer,String> out=direct(api,safe);if(out.isEmpty())out=probeUrl(safe,url);if(!out.isEmpty())return out;}catch(Exception ignored){}}throw new IOException("Просмотр не открыл подходящий вариант");}
    private static ArrayList<String> frames(String base,String page){LinkedHashSet<String> out=new LinkedHashSet<>();String text=normalizePayload(page);Matcher tag=Pattern.compile("<(?:iframe|embed)[^>]+(?:src|data-src|data-url)=[\"']([^\"']+)[\"']",Pattern.CASE_INSENSITIVE).matcher(text);while(tag.find())addFrame(out,base,tag.group(1));Matcher js=Pattern.compile("(?:iframe|player|embed|src)\\s*[:=]\\s*[\"'](https?:[^\"']+|//[^\"']+)[\"']",Pattern.CASE_INSENSITIVE).matcher(text);while(js.find())addFrame(out,base,js.group(1));return new ArrayList<>(out);}
    private static void addFrame(LinkedHashSet<String> out,String base,String raw){String safe=absolute(base,normalizePayload(raw));if(safe.isEmpty()||streamLike(safe))return;String h=host(safe),p=path(safe).toLowerCase(Locale.ROOT);if(h.contains("doubleclick")||h.contains("adfox")||h.contains("yandex")||h.contains("google")||h.contains("facebook"))return;boolean likely=h.contains("kodik")||h.contains("aniqit")||h.contains("yani")||h.contains("cdnvideohub")||h.contains("aksor")||h.contains("sibnet")||h.contains("vk")||h.contains("rutube")||h.contains("aniboom")||p.contains("player")||p.contains("embed")||p.contains("iframe")||p.contains("watch")||p.contains("video");if(likely&&out.size()<8)out.add(safe);}
    private static TreeMap<Integer,String> probeUrl(String url,String referer){TreeMap<Integer,String> out=new TreeMap<>();String safe=ApiRepository.safeUrl(url);if(safe.isEmpty())return out;try{TaskQueue.check();HashMap<String,String> h=new HashMap<>();if(referer!=null&&!referer.isEmpty())h.put("Referer",referer);h.put("Range","bytes=0-8191");byte[] data=Net.bytes(safe,h,"video/*,application/vnd.apple.mpegurl,application/dash+xml,*/*;q=0.5",CHROME,"",2200,3200,8192);String head=data.length>0?new String(data,0,Math.min(data.length,8192),StandardCharsets.ISO_8859_1):"";boolean ok=head.startsWith("#EXTM3U")||head.contains("<MPD")||head.contains("ftyp");if(ok)out.put(quality(safe),safe);}catch(Exception ignored){}return clean(out);}
    private static TreeMap<Integer,String> clean(TreeMap<Integer,String> input){TreeMap<Integer,String> out=new TreeMap<>();for(Map.Entry<Integer,String> e:input.entrySet()){String s=ApiRepository.safeUrl(e.getValue());if(!s.isEmpty())out.put(e.getKey()==null?0:e.getKey(),s);}return out;}
    private static HashMap<String,String> headers(String origin,String referer){HashMap<String,String> h=new HashMap<>();h.put("Origin",origin);h.put("Referer",referer);h.put("Accept-Language","ru-RU,ru;q=0.9,en;q=0.5");h.put("User-Agent",CHROME);return h;}
    private static String origin(String url){try{Uri u=Uri.parse(url);return u.getScheme()+"://"+u.getHost();}catch(Exception e){return "https://yani.tv";}}
    private static String absolute(String base,String value){try{if(value==null||value.trim().isEmpty())return "";value=value.trim().replace("&amp;","&").replace("\\/","/");if(value.startsWith("//"))value="https:"+value;return ApiRepository.safeUrl(new URL(new URL(base),value).toString());}catch(Exception e){return "";}}
    private static String find(String input,String regex){Matcher m=Pattern.compile(regex,Pattern.CASE_INSENSITIVE|Pattern.DOTALL).matcher(input);return m.find()?unescape(m.group(1)):"";}
    private static String first(String a,String b){return a!=null&&!a.isEmpty()?a:b==null?"":b;}
    private static int parseInt(String value){try{return Integer.parseInt(value==null?"0":value.replaceAll("\\D+",""));}catch(Exception e){return 0;}}
    private static int quality(String url){Matcher m=Pattern.compile("(?:^|[^0-9])([1-9][0-9]{2,3})p?(?:[^0-9]|$)").matcher(url);int q=0;while(m.find()){try{int v=Integer.parseInt(m.group(1));if(v>=240&&v<=4320)q=v;}catch(Exception ignored){}}return q;}
    private static String decode(String src)throws Exception{if(src==null||src.isEmpty())return "";if(src.contains("//")||src.startsWith("http"))return fixProtocol(src);String caesar=caesar(src);int mod=caesar.length()%4;if(mod!=0)caesar=caesar+"====".substring(mod);return new String(Base64.decode(caesar,Base64.DEFAULT),StandardCharsets.UTF_8);}
    private static String caesar(String input){StringBuilder out=new StringBuilder();for(int i=0;i<input.length();i++){char ch=input.charAt(i);if(ch>='a'&&ch<='z')out.append((char)((ch-'a'+SHIFT)%26+'a'));else if(ch>='A'&&ch<='Z')out.append((char)((ch-'A'+SHIFT)%26+'A'));else out.append(ch);}return out.toString();}
    private static String fixProtocol(String s){if(s==null)return "";s=s.trim().replace("\\/","/").replace("&amp;","&");return s.startsWith("//")?"https:"+s:s;}
    private static String endpointPath(String script){Matcher m=Pattern.compile("atob\\(\"([A-Za-z0-9+/=]+)\"\\)").matcher(script);while(m.find())try{String decoded=new String(Base64.decode(m.group(1),Base64.DEFAULT),StandardCharsets.UTF_8);if(decoded.startsWith("/")&&!decoded.startsWith("//")&&decoded.length()<=16)return decoded;}catch(Exception ignored){}return "";}
    private static void add(StringBuilder body,String key,String value,boolean raw){if(body.length()>0)body.append('&');body.append(enc(key)).append('=').append(raw?value:enc(value));}
    private static boolean looksEncoded(String s){return s!=null&&s.matches(".*%[0-9A-Fa-f]{2}.*");}
    private static String unescape(String s){return s==null?"":s.replace("&quot;","\"").replace("&#34;","\"").replace("&#039;","'").replace("&amp;","&").replace("\\/","/");}
    private static String enc(String s){try{return URLEncoder.encode(s==null?"":s,"UTF-8");}catch(Exception e){return "";}}
    private static final class Page {String text="",cookies="";}
    private static Page fetch(String url,String referer)throws Exception{String safe=ApiRepository.safeUrl(url);if(safe.isEmpty())throw new IOException("Недопустимый адрес");TaskQueue.check();try{Net.Page loaded=Net.page(safe,referer,CHROME,"text/html,application/xhtml+xml,application/json,*/*;q=0.8",4500,6500,12*1024*1024);Page p=new Page();p.text=loaded.text;p.cookies=loaded.cookies;return p;}catch(Net.HttpCode e){throw new IOException("Просмотр не ответил");}}

    private static String postJson(String url,String body,String referer,String cookies)throws Exception{HashMap<String,String> h=headers(origin(url),referer);h.put("Accept","application/json, text/javascript, */*; q=0.01");h.put("X-Requested-With","XMLHttpRequest");if(cookies!=null&&!cookies.isEmpty())h.put("Cookie",cookies);String safe=ApiRepository.safeUrl(url);if(safe.isEmpty())throw new IOException("Недопустимый адрес");TaskQueue.check();try{return Net.text(safe,"POST",body,false,h,null,CHROME,4500,6500,12*1024*1024);}catch(Net.HttpCode e){throw new IOException("Просмотр не ответил");}}
    private static String post(String url,String body,String referer,String cookies)throws Exception{HashMap<String,String> h=headers(origin(url),referer);h.put("Accept","application/json, text/javascript, */*; q=0.01");h.put("X-Requested-With","XMLHttpRequest");if(cookies!=null&&!cookies.isEmpty())h.put("Cookie",cookies);String safe=ApiRepository.safeUrl(url);if(safe.isEmpty())throw new IOException("Недопустимый адрес");TaskQueue.check();try{return Net.text(safe,"POST",body,true,h,null,CHROME,4500,6500,12*1024*1024);}catch(Net.HttpCode e){throw new IOException("Просмотр не ответил");}}
}
