package com.tsuyu.line;

import android.content.*;
import android.database.Cursor;
import android.database.sqlite.*;
import org.json.*;
import java.util.*;
import java.util.concurrent.*;

public final class YoruCache extends SQLiteOpenHelper {
    private static final String DB="yoru-fast-cache.db";private static final int VERSION=2;
    private static final long DAY=24L*60*60*1000,TRIM_INTERVAL=60L*60L*1000L;
    private final ConcurrentHashMap<String,Long> trimAt=new ConcurrentHashMap<>();
    private volatile int cachedTodayCount=-1;private volatile long cachedTodayAt,cachedTodayDay;
    public YoruCache(Context c){super(c.getApplicationContext(),DB,null,VERSION);try{setWriteAheadLoggingEnabled(true);}catch(Exception ignored){}}
    @Override public void onCreate(SQLiteDatabase db){
        db.execSQL("CREATE TABLE IF NOT EXISTS details(k TEXT PRIMARY KEY, mal INTEGER, json TEXT NOT NULL, updated INTEGER NOT NULL)");
        db.execSQL("CREATE INDEX IF NOT EXISTS details_mal ON details(mal)");
        db.execSQL("CREATE TABLE IF NOT EXISTS schedule(k TEXT PRIMARY KEY, json TEXT NOT NULL, updated INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE IF NOT EXISTS franchise(mal INTEGER PRIMARY KEY, json TEXT NOT NULL, updated INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE IF NOT EXISTS shots(mal INTEGER PRIMARY KEY, json TEXT NOT NULL, updated INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE IF NOT EXISTS offline(k TEXT PRIMARY KEY, json TEXT NOT NULL, updated INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE IF NOT EXISTS progress(k TEXT PRIMARY KEY, json TEXT NOT NULL, updated INTEGER NOT NULL)");db.execSQL("CREATE TABLE IF NOT EXISTS henta(k TEXT PRIMARY KEY, json TEXT NOT NULL, updated INTEGER NOT NULL)");
    }
    @Override public void onUpgrade(SQLiteDatabase db,int oldVersion,int newVersion){onCreate(db);}
    public static String key(Anime a){if(a==null)return "";if(a.malId>0)return Sec.s("39121943")+a.malId;if(a.source!=null&&a.source.equals(Sec.s("271b1c121c3e0a111b"))){try{int m=Integer.parseInt(a.id);if(m>0)return Sec.s("39121943")+m;}catch(Exception ignored){}}if(a.anilistId>0)return Sec.s("351d1c43")+a.anilistId;if(a.kpId>0)return "kp:"+a.kpId;String k=a.key();return k==null?"":k;}
    public Anime detail(Anime base,long ttl){String k=key(base);if(k.isEmpty())return null;long min=System.currentTimeMillis()-Math.max(60_000,ttl);Cursor c=null;try{SQLiteDatabase db=getReadableDatabase();c=db.rawQuery("SELECT json FROM details WHERE k=? AND updated>=?",new String[]{k,String.valueOf(min)});int mal=base!=null?base.malId:0;if(mal<=0&&base!=null&&Sec.s("271b1c121c3e0a111b").equals(base.source)){try{mal=Integer.parseInt(base.id);}catch(Exception ignored){}}if(!c.moveToFirst()&&mal>0){close(c);c=db.rawQuery("SELECT json FROM details WHERE mal=? AND updated>=? ORDER BY updated DESC LIMIT 1",new String[]{String.valueOf(mal),String.valueOf(min)});if(!c.moveToFirst())return null;}Anime a=unpack(new JSONObject(c.getString(0)));return Anime.valid(a)?a:null;}catch(Exception e){return null;}finally{close(c);}}
    public void detail(Anime a){if(!Anime.valid(a))return;try{SQLiteDatabase db=getWritableDatabase();String k=key(a);int mal=a.malId>0?a.malId:0;if(mal<=0&&Sec.s("271b1c121c3e0a111b").equals(a.source)){try{mal=Integer.parseInt(a.id);}catch(Exception ignored){}}Cursor c=db.rawQuery("SELECT json FROM details WHERE k=? LIMIT 1",new String[]{k});if(!c.moveToFirst()&&mal>0){close(c);c=db.rawQuery("SELECT json FROM details WHERE mal=? ORDER BY updated DESC LIMIT 1",new String[]{String.valueOf(mal)});}if(c.moveToFirst()){JSONObject old=new JSONObject(c.getString(0));if(a.description.isEmpty()&&old.has("description")&&!old.optString("description","").isEmpty()){a.description=old.optString("description","");}if(a.poster.isEmpty()&&old.has("poster")&&!old.optString("poster","").isEmpty()){a.poster=old.optString("poster","");}if(a.score<=0&&old.has("score")){a.score=old.optDouble("score",0);}if(a.episodes<=0&&old.has("episodesTotal")){a.episodes=old.optInt("episodesTotal",0);}if(a.episodesAired<=0&&old.has("episodesAired")){a.episodesAired=old.optInt("episodesAired",0);}if(a.episodeList.isEmpty()){JSONArray eps=old.optJSONArray("eps");if(eps!=null&&eps.length()>0){for(int i=0;i<eps.length();i++){Anime.Episode ep=unpackEpisode(eps.optJSONObject(i));boolean hasContent=ep!=null&&(!ep.streams.isEmpty()||!ep.variants.isEmpty()||(ep.lazy!=null&&!ep.lazy.isEmpty()&&!"future".equals(ep.lazy))||(ep.resolverUrl!=null&&!ep.resolverUrl.isEmpty()));if(hasContent){ep.future=false;a.episodeList.add(ep);}}}}}close(c);if(a.description.isEmpty()&&mal>0){Cursor mc=null;try{mc=db.rawQuery("SELECT json FROM details WHERE mal=? AND json LIKE '%\"description\":\"_%' ORDER BY updated DESC LIMIT 1",new String[]{String.valueOf(mal)});if(mc.moveToFirst()){JSONObject mo=new JSONObject(mc.getString(0));String md=mo.optString("description","");if(!md.isEmpty())a.description=md;}}catch(Exception ignored){}finally{close(mc);}}ContentValues v=new ContentValues();v.put("k",key(a));v.put("mal",a.malId);v.put("json",pack(a).toString());v.put("updated",System.currentTimeMillis());db.insertWithOnConflict("details",null,v,SQLiteDatabase.CONFLICT_REPLACE);trimMaybe(db,"details",520,14*DAY);}catch(Exception ignored){}}
    public JSONArray schedule(long ttl){return jsonArray("schedule","main2",ttl);}
    public void schedule(JSONArray rows){cachedTodayCount=-1;putJson("schedule","main2",rows==null?new JSONArray():rows,4*DAY,6);}
    public JSONArray franchise(int mal,long ttl){if(mal<=0)return new JSONArray();return jsonArray("franchise",String.valueOf(mal),ttl);}
    public void franchise(int mal,JSONArray rows){if(mal<=0)return;putJson("franchise",String.valueOf(mal),rows==null?new JSONArray():rows,21*DAY,240);}
    public JSONArray animeShots(int mal,long ttl){if(mal<=0)return new JSONArray();return jsonArray("animeShots",String.valueOf(mal),ttl);}
    public void animeShots(int mal,JSONArray rows){if(mal<=0)return;putJson("animeShots",String.valueOf(mal),rows==null?new JSONArray():rows,21*DAY,240);}
    public JSONArray shots(int mal,long ttl){if(mal<=0)return new JSONArray();return jsonArray("shots",String.valueOf(mal),ttl);}
    public void shots(int mal,JSONArray rows){if(mal<=0)return;putJson("shots",String.valueOf(mal),rows==null?new JSONArray():rows,21*DAY,240);}
    public String offline(long ttl){JSONArray arr=jsonArray("offline","index",ttl);return arr.toString();}
    public void offline(String json){try{putJson("offline","index",new JSONArray(json==null||json.isEmpty()?"[]":json),7*DAY,4);}catch(Exception ignored){}}
    public void progressMirror(String k,JSONObject row){if(k==null||k.isEmpty()||row==null)return;try{SQLiteDatabase db=getWritableDatabase();ContentValues v=new ContentValues();v.put("k",k);v.put("json",row.toString());v.put("updated",System.currentTimeMillis());db.insertWithOnConflict("progress",null,v,SQLiteDatabase.CONFLICT_REPLACE);trimMaybe(db,"progress",1200,60*DAY);}catch(Exception ignored){}}
    public int todayScheduleCount(){long now=System.currentTimeMillis();Calendar c=Calendar.getInstance(java.util.TimeZone.getTimeZone("Europe/Moscow"));c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);long start=c.getTimeInMillis();if(cachedTodayCount>=0&&cachedTodayDay==start&&now-cachedTodayAt<60_000L)return cachedTodayCount;JSONArray arr=schedule(3*60*60*1000L);long end=start+DAY;int n=0;for(int i=0;i<arr.length();i++){JSONObject j=arr.optJSONObject(i);long t=j==null?0:j.optLong("time");if(t>=start&&t<end)n++;}cachedTodayCount=n;cachedTodayDay=start;cachedTodayAt=now;return n;}
    public void trimNow(){try{SQLiteDatabase db=getWritableDatabase();trim(db,"details",520,14*DAY);trim(db,"franchise",240,21*DAY);trim(db,"shots",240,21*DAY);trim(db,"schedule",6,4*DAY);trim(db,"offline",4,7*DAY);trim(db,"progress",1200,60*DAY);long now=System.currentTimeMillis();trimAt.put("details",now);trimAt.put("franchise",now);trimAt.put("shots",now);trimAt.put("schedule",now);trimAt.put("offline",now);trimAt.put("progress",now);}catch(Exception ignored){}}
    private static boolean malKey(String table){return table.equals("franchise")||table.equals("shots");}
    private JSONArray jsonArray(String table,String k,long ttl){Cursor c=null;try{SQLiteDatabase db=getReadableDatabase();long min=System.currentTimeMillis()-Math.max(60_000,ttl);String keyColumn=malKey(table)?"mal":"k";c=db.rawQuery("SELECT json FROM "+table+" WHERE "+keyColumn+"=? AND updated>=?",new String[]{k,String.valueOf(min)});if(!c.moveToFirst())return new JSONArray();return new JSONArray(c.getString(0));}catch(Exception e){return new JSONArray();}finally{close(c);}}
    public JSONArray hentaJson(String k,long ttl){return jsonArray("henta",k,ttl);}
    public void hentaPut(String k,JSONArray rows,long age){putJson("henta",k,rows,age,60);}
    private void putJson(String table,String k,JSONArray rows,long age,int keep){try{SQLiteDatabase db=getWritableDatabase();ContentValues v=new ContentValues();if(malKey(table))v.put("mal",Integer.parseInt(k));else v.put("k",k);v.put("json",rows.toString());v.put("updated",System.currentTimeMillis());db.insertWithOnConflict(table,null,v,SQLiteDatabase.CONFLICT_REPLACE);trimMaybe(db,table,keep,age);}catch(Exception ignored){}}
    private void trimMaybe(SQLiteDatabase db,String table,int keep,long maxAge){long now=System.currentTimeMillis();Long last=trimAt.get(table);if(last!=null&&now-last<TRIM_INTERVAL)return;trimAt.put(table,now);YoruApp app=YoruApp.app();if(app!=null&&app.discovery!=null)app.discovery.execute(()->{try{SQLiteDatabase writable=getWritableDatabase();trim(writable,table,keep,maxAge);}catch(Exception ignored){}});}
    private static JSONObject pack(Anime a)throws JSONException{JSONObject j=a.json();JSONArray rel=new JSONArray();for(Anime r:a.related)if(Anime.valid(r)&&rel.length()<120)rel.put(r.json());j.put("related",rel);if(!a.episodeList.isEmpty())j.put("eps",packEpisodes(a));return j;}
    private static JSONArray packEpisodes(Anime a)throws JSONException{JSONArray arr=new JSONArray();for(Anime.Episode e:a.episodeList){if(e==null||arr.length()>=400)break;JSONObject j=new JSONObject();j.put("id",e.id);j.put("n",e.number);if(!e.name.isEmpty())j.put("t",e.name);if(!e.lazy.isEmpty())j.put("lz",e.lazy);if(!e.resolverUrl.isEmpty())j.put("ru",e.resolverUrl);if(!e.poster.isEmpty())j.put("p",e.poster);if(!e.airDate.isEmpty())j.put("ad",e.airDate);if(e.duration>0)j.put("d",e.duration);if(e.openingStart>0)j.put("os",e.openingStart);if(e.openingEnd>0)j.put("oe",e.openingEnd);if(e.future)j.put("f",1);if(!e.streams.isEmpty()){JSONObject s=new JSONObject();for(Map.Entry<Integer,String> en:e.streams.entrySet())if(en.getKey()!=null&&en.getValue()!=null&&!en.getValue().isEmpty())s.put(String.valueOf(en.getKey()),en.getValue());if(s.length()>0)j.put("s",s);}if(!e.variants.isEmpty()){JSONArray vs=new JSONArray();for(Anime.Variant v:e.variants){if(v==null||vs.length()>=16)break;JSONObject o=new JSONObject();o.put("n",v.name);o.put("p",v.player);o.put("u",v.url);if(!v.displayName.isEmpty())o.put("dn",v.displayName);if(v.duration>0)o.put("d",v.duration);if(v.openingStart>0)o.put("os",v.openingStart);if(v.openingEnd>0)o.put("oe",v.openingEnd);vs.put(o);}if(vs.length()>0)j.put("v",vs);}arr.put(j);}return arr;}
    private static Anime.Episode unpackEpisode(JSONObject j){Anime.Episode e=new Anime.Episode();if(j==null)return e;e.id=j.optString("id","");e.number=j.optDouble("n",0);e.name=j.optString("t","");e.lazy=j.optString("lz","");e.resolverUrl=j.optString("ru","");e.poster=ApiRepository.safeUrl(j.optString("p",""));e.airDate=j.optString("ad","");e.duration=j.optInt("d",0);e.openingStart=j.optInt("os",0);e.openingEnd=j.optInt("oe",0);e.future=j.optInt("f",0)==1;JSONObject s=j.optJSONObject("s");if(s!=null){Iterator<String> it=s.keys();while(it.hasNext()){String k=it.next();try{int q=Integer.parseInt(k);String u=ApiRepository.safeUrl(s.optString(k,""));if(!u.isEmpty())e.streams.put(q,u);}catch(Exception ignored){}}}JSONArray vs=j.optJSONArray("v");for(int i=0;vs!=null&&i<vs.length();i++){JSONObject o=vs.optJSONObject(i);if(o==null)continue;Anime.Variant v=new Anime.Variant(o.optString("n",""),o.optString("p",""),o.optString("u",""));v.displayName=o.optString("dn","");v.duration=o.optInt("d",0);v.openingStart=o.optInt("os",0);v.openingEnd=o.optInt("oe",0);e.variants.add(v);}return e;}
    private static Anime unpack(JSONObject j){Anime a=Anime.from(j);JSONArray rel=j.optJSONArray("related");for(int i=0;rel!=null&&i<rel.length()&&a.related.size()<120;i++){Anime r=Anime.from(rel.optJSONObject(i));if(Anime.valid(r)&&!r.key().equals(a.key()))a.related.add(r);}JSONArray eps=j.optJSONArray("eps");for(int i=0;eps!=null&&i<eps.length()&&a.episodeList.size()<400;i++){Anime.Episode e=unpackEpisode(eps.optJSONObject(i));if(e!=null)a.episodeList.add(e);}return a;}
    private static void trim(SQLiteDatabase db,String table,int keep,long maxAge){long min=System.currentTimeMillis()-maxAge;try{db.delete(table,"updated<?",new String[]{String.valueOf(min)});}catch(Exception ignored){}Cursor c=null;try{String keyColumn=malKey(table)?"mal":"k";c=db.rawQuery("SELECT "+keyColumn+" FROM "+table+" ORDER BY updated DESC LIMIT -1 OFFSET "+Math.max(1,keep),null);ArrayList<String> old=new ArrayList<>();while(c.moveToNext())old.add(c.getString(0));close(c);for(String k:old)db.delete(table,keyColumn+"=?",new String[]{k});}catch(Exception ignored){close(c);}}
    private static void close(Cursor c){try{if(c!=null)c.close();}catch(Exception ignored){}}
}
