package com.tsuyu.line;

import org.json.*;
import java.util.*;

final class YoruBrain {
    private YoruBrain(){}
    private static volatile JSONObject cachedStats;private static volatile long cachedStatsAt;
    static String title(Anime a){if(a==null)return "Аниме";try{if(YoruApp.app()!=null&&YoruApp.app().store.originalTitles()&&!a.original.isEmpty())return a.original;}catch(Exception ignored){}return a.title;}
    static boolean visible(Anime a){if(!Anime.valid(a))return false;SecureStore s=YoruApp.app().store;if(s.hidden(a))return false;if(s.hideSeen()&&"completed".equals(s.bucket(a)))return false;return true;}
    static ArrayList<Anime> visible(Collection<Anime> rows){LinkedHashMap<String,Anime> out=new LinkedHashMap<>();SecureStore s=YoruApp.app().store;boolean hideSeen=s.hideSeen();if(rows!=null)for(Anime a:rows){if(!Anime.valid(a))continue;if(s.hidden(a))continue;if(hideSeen&&"completed".equals(s.bucket(a)))continue;out.put(a.key(),a);}return new ArrayList<>(out.values());}
    static ArrayList<Anime> shelf(String kind,int max){SecureStore store=YoruApp.app().store;ArrayList<Anime> base=new ArrayList<>();base.addAll(YoruApp.app().api.seed());base.addAll(store.favorites());base.addAll(store.recent());ArrayList<Anime> out=new ArrayList<>();HashMap<String,Integer> scores=new HashMap<>();for(Anime a:visible(base)){String t=text(a);boolean ok=false;if("forYou".equals(kind))ok=taste(a)>0;if("short".equals(kind))ok=a.episodes>0&&a.episodes<=13||a.type.toLowerCase(Locale.ROOT).contains("фильм");if("movies".equals(kind))ok=a.type.toLowerCase(Locale.ROOT).contains("фильм");if("ongoing".equals(kind))ok="ongoing".equals(a.status)||"anons".equals(a.status);if("classics".equals(kind))ok=a.year>0&&a.year<2015&&a.score>=7;if("gems".equals(kind))ok=a.score>=7.5&&!store.favorite(a);if("pinned".equals(kind))ok=store.pinned(a);if("rewatch".equals(kind))ok=store.rewatch(a)>0||"completed".equals(store.bucket(a));if("romance".equals(kind))ok=t.contains("роман");if("action".equals(kind))ok=t.contains("экшен")||t.contains("приключ");if("calm".equals(kind))ok=t.contains("повсед")||t.contains("комед")||t.contains("слайс");if(ok){out.add(a);scores.put(a.key(),score(a,kind));}}out.sort((a,b)->Integer.compare(scores.getOrDefault(b.key(),0),scores.getOrDefault(a.key(),0)));return limit(unique(out),max);}
    static ArrayList<Anime> similar(Anime source,int max){ArrayList<Anime> out=new ArrayList<>();if(source==null)return out;HashMap<String,Integer> scores=new HashMap<>();for(Anime a:visible(YoruApp.app().api.seed())){if(a.key().equals(source.key()))continue;int s=simScore(source,a);if(s>0){out.add(a);scores.put(a.key(),s);}}out.sort((a,b)->Integer.compare(scores.getOrDefault(b.key(),0),scores.getOrDefault(a.key(),0)));return limit(unique(out),max);}
    static Anime surprise(){ArrayList<Anime> rows=shelf("forYou",50);if(rows.isEmpty())rows=visible(YoruApp.app().api.seed());if(rows.isEmpty())return null;return rows.get(new Random().nextInt(rows.size()));}
    static String dashboard(){JSONObject s=YoruApp.app().store.stats();long minutes=Math.max(0,s.optLong("seconds")/60);String time=minutes>=60?minutes/60+" ч "+minutes%60+" мин":minutes+" мин";return "В коллекции: "+s.optInt("favorites")+" · в плане: "+s.optInt("queue")+"\nИстория: "+s.optInt("titles")+" тайтлов · "+s.optInt("episodes")+" серий · "+time;}
    static String chip(Anime a){SecureStore s=YoruApp.app().store;if(s.pinned(a))return "Закреплено";int r=s.rating(a);if(r>0)return "Ваша оценка "+r+"/10";if(s.rewatch(a)>0)return "Пересмотр · "+s.rewatch(a);JSONObject h=s.progress(a);if(h.length()>0)return "Продолжить · серия "+Ui.number(h.optDouble("episode",1));if(s.favorite(a))return "В коллекции";if("ongoing".equals(a.status)){int n=a.aired();return n>0?"Онгоинг "+n+" серия":"Онгоинг";}String e=a.episodesLine();if(!e.isEmpty())return e;if(a.score>0)return "★ "+String.format(java.util.Locale.US,"%.1f",a.score);return "";}

    static ArrayList<Anime> newEpisodes(int max){SecureStore store=YoruApp.app().store;LinkedHashMap<String,Anime> map=new LinkedHashMap<>();for(Anime a:store.favorites()){if(!visible(a))continue;JSONObject h=store.progress(a);double seen=h.optDouble("episode",0);int aired=a.aired();if(aired<=0)aired=a.episodes;boolean hasNew=seen>0&&aired>seen+0.001;if(!hasNew&&"watching".equals(store.bucket(a))&&a.ongoing())hasNew=true;if(hasNew)map.put(a.key(),a);}ArrayList<Anime> out=new ArrayList<>(map.values());out.sort((a,b)->Integer.compare(newEpisodeScore(b),newEpisodeScore(a)));return limit(out,max);}
    private static int newEpisodeScore(Anime a){JSONObject h=YoruApp.app().store.progress(a);int aired=Math.max(a.aired(),a.episodes);int unseen=(int)Math.max(0,Math.ceil(aired-h.optDouble("episode",0)));int score=unseen*20;if(a.ongoing())score+=35;if(YoruApp.app().store.pinned(a))score+=25;if(h.length()>0)score+=15;score+=Math.min(20,(int)Math.round(a.score));return score;}

    static String personalLine(Anime a){SecureStore s=YoruApp.app().store;ArrayList<String> rows=new ArrayList<>();int r=s.rating(a);if(r>0)rows.add("оценка "+r+"/10");String tags=s.tags(a);if(!tags.isEmpty())rows.add(tags);int rw=s.rewatch(a);if(rw>0)rows.add("пересмотров: "+rw);return rows.isEmpty()?"":String.join(" · ",rows);}

    static ArrayList<Anime> priorities(int max){LinkedHashMap<String,Anime> rows=new LinkedHashMap<>();for(Anime a:YoruApp.app().store.watchQueue())if(visible(a))rows.put(a.key(),a);for(Anime a:YoruApp.app().store.recent())if(visible(a))rows.put(a.key(),a);for(Anime a:YoruApp.app().store.favorites())if(visible(a))rows.put(a.key(),a);ArrayList<Anime> out=new ArrayList<>(rows.values());out.sort((a,b)->Integer.compare(priorityScore(b),priorityScore(a)));return limit(out,max);}
    static ArrayList<Anime> marathon(int max){ArrayList<Anime> out=new ArrayList<>();for(Anime a:visible(YoruApp.app().store.watchQueue()))if(a.episodes==0||a.episodes<=24||YoruApp.app().store.progress(a).length()>0)out.add(a);for(Anime a:shelf("short",40))if(!out.contains(a))out.add(a);out.sort((a,b)->Integer.compare(marathonScore(b),marathonScore(a)));return limit(unique(out),max);}
    static String tasteMap(){JSONObject s=YoruApp.app().store.stats();JSONArray gs=s.optJSONArray("genres");ArrayList<String> lines=new ArrayList<>();for(int i=0;gs!=null&&i<Math.min(5,gs.length());i++)lines.add((i+1)+". "+gs.optString(i));String mood=s.optInt("episodes")>=80?"уверенный марафон":s.optInt("favorites")>=8?"собранная коллекция":s.optInt("queue")>=3?"плановое настроение":"поиск вкуса";return "Профиль: "+mood+"\n"+(lines.isEmpty()?"Жанры появятся после просмотра, оценок и тегов":"Жанры:\n"+String.join("\n",lines));}
    static String[] libraryDoctor(){SecureStore store=YoruApp.app().store;JSONObject s=store.stats();ArrayList<String> rows=new ArrayList<>();int queue=s.optInt("queue"),hidden=s.optInt("hidden"),ratings=s.optInt("ratings"),pins=s.optInt("pins");rows.add("План просмотра — "+(queue==0?"можно добавить тайтлы, которые хотите посмотреть позже":"в плане "+queue+" тайтлов"));rows.add("Оценки — "+(ratings==0?"помогают точнее сортировать личные рекомендации":"оценено тайтлов: "+ratings));rows.add("Закрепления — "+(pins==0?"закрепите важное, чтобы оно было выше":"закреплено: "+pins));rows.add("Скрытые тайтлы — "+(hidden>0?String.valueOf(hidden):"нет"));int duplicates=duplicateCount();rows.add("Похожие карточки — "+(duplicates==0?"явных повторов не найдено":"найдено: "+duplicates));int stale=staleCount();rows.add("Долгие паузы — "+(stale==0?"активных пауз нет":"можно вернуться к "+stale+" тайтлам"));return rows.toArray(new String[0]);}
    static ArrayList<Anime> restartList(int max){ArrayList<Anime> out=new ArrayList<>();long edge=System.currentTimeMillis()-21L*24*60*60*1000;for(Anime a:YoruApp.app().store.recent()){JSONObject h=YoruApp.app().store.progress(a);if(h.optLong("updated")>0&&h.optLong("updated")<edge&&visible(a))out.add(a);}out.sort((a,b)->Long.compare(YoruApp.app().store.progress(a).optLong("updated"),YoruApp.app().store.progress(b).optLong("updated")));return limit(unique(out),max);}
    static ArrayList<Anime> watchOrder(Anime source){ArrayList<Anime> rows=new ArrayList<>();if(source==null)return rows;rows.add(source);rows.addAll(source.related);for(Anime a:similar(source,12))if(a.year>0&&source.year>0&&Math.abs(a.year-source.year)<=8)rows.add(a);ArrayList<Anime> out=unique(rows);out.sort((a,b)->{int y=Integer.compare(a.year==0?9999:a.year,b.year==0?9999:b.year);if(y!=0)return y;return YoruBrain.title(a).compareToIgnoreCase(YoruBrain.title(b));});return limit(out,24);}
    static String nextHint(Anime a){if(a==null)return "Откройте карточку и выберите просмотр";JSONObject h=YoruApp.app().store.progress(a);if(h.length()==0)return "Начать с первой серии";double ep=h.optDouble("episode",1);int time=h.optInt("time",0);String seen=a.episodes>0&&ep>=a.episodes?"финал отмечен":"продолжить серию "+Ui.number(ep);return seen+" · "+Ui.time(time);}
    private static int priorityScore(Anime a){SecureStore store=YoruApp.app().store;int s=score(a,"forYou");if(store.pinned(a))s+=120;if(store.watchQueue().contains(a))s+=60;JSONObject h=store.progress(a);if(h.length()>0)s+=40;if("watching".equals(store.bucket(a)))s+=35;if("ongoing".equals(a.status))s+=20;if(a.episodes>0&&a.episodes<=13)s+=12;return s;}
    private static int marathonScore(Anime a){int s=priorityScore(a);if(a.episodes>0)s+=Math.max(0,30-a.episodes);if(a.type.toLowerCase(Locale.ROOT).contains("фильм"))s+=35;return s;}
    private static int duplicateCount(){HashMap<String,Integer> seen=new HashMap<>();int dup=0;ArrayList<Anime> all=new ArrayList<>();all.addAll(YoruApp.app().store.favorites());all.addAll(YoruApp.app().store.recent());for(Anime a:all){String key=a.malId>0?"mal:"+a.malId:ApiRepository.plainName(a.title);if(key.isEmpty())continue;int n=seen.getOrDefault(key,0)+1;seen.put(key,n);if(n==2)dup++;}return dup;}
    private static int staleCount(){long edge=System.currentTimeMillis()-21L*24*60*60*1000;int n=0;for(Anime a:YoruApp.app().store.recent()){JSONObject h=YoruApp.app().store.progress(a);if(h.optLong("updated")>0&&h.optLong("updated")<edge&&visible(a))n++;}return n;}
    private static int score(Anime a,String kind){int s=taste(a)*3+(int)Math.round(a.score*10);if(YoruApp.app().store.favorite(a))s+=30;if(YoruApp.app().store.pinned(a))s+=80;if("short".equals(kind)&&a.episodes>0)s+=Math.max(0,20-a.episodes);if("ongoing".equals(kind)&&"ongoing".equals(a.status))s+=50;return s;}
    private static JSONObject stats(){long now=System.currentTimeMillis();JSONObject s=cachedStats;if(s!=null&&now-cachedStatsAt<2500)return s;s=YoruApp.app().store.stats();cachedStats=s;cachedStatsAt=now;return s;}
    private static int taste(Anime a){JSONObject st=stats();JSONArray gs=st.optJSONArray("genres");int score=0;HashSet<String> have=genreSet(a);for(int i=0;gs!=null&&i<gs.length();i++)if(have.contains(norm(gs.optString(i))))score+=5-i;String tags=YoruApp.app().store.tags(a);if(!tags.isEmpty())score+=2;return score;}
    private static int simScore(Anime source,Anime a){int s=0;if(!source.studio.isEmpty()&&source.studio.equalsIgnoreCase(a.studio))s+=6;if(source.year>0&&Math.abs(source.year-a.year)<=2)s++;HashSet<String> have=genreSet(a);for(String g:source.genres)if(have.contains(norm(g)))s+=2;return s;}
    private static HashSet<String> genreSet(Anime a){HashSet<String> out=new HashSet<>();if(a!=null)for(String g:a.genres)out.add(norm(g));return out;}
    private static String norm(String s){return s==null?"":s.trim().toLowerCase(Locale.ROOT);}
    private static String text(Anime a){return (a.title+" "+a.original+" "+a.type+" "+a.status+" "+a.age+" "+a.studio+" "+String.join(" ",a.genres)).toLowerCase(Locale.ROOT);}
    private static ArrayList<Anime> unique(Collection<Anime> in){LinkedHashMap<String,Anime> out=new LinkedHashMap<>();for(Anime a:in)if(Anime.valid(a))out.put(a.key(),a);return new ArrayList<>(out.values());}
    private static ArrayList<Anime> limit(ArrayList<Anime> rows,int max){if(rows.size()<=max)return rows;return new ArrayList<>(rows.subList(0,max));}
}
