package com.tsuyu.line;

import android.util.JsonReader;
import android.util.JsonToken;
import java.io.*;
import java.net.*;
import java.util.*;

final class YummyParser {
    static ArrayList<Anime.Episode> episodes(String id)throws Exception{
TreeMap<Double,Anime.Episode> groups=new TreeMap<>();HashMap<Double,HashSet<String>> seen=new HashMap<>();
        try(Net.Body body=Net.open(Sec.s("3c07010906694a4c13151d651c185c591c42225c14171c3e004c")+id+"/videos",null,"application/json","Tsuyu-Android/2.1",3500,7000);JsonReader r=new JsonReader(new InputStreamReader(body.input(),java.nio.charset.StandardCharsets.UTF_8))){r.beginObject();boolean response=false;int records=0;while(r.hasNext()){String name=r.nextName();if(!name.equals("response")){if(name.equals("error")){String error=text(r);if(!error.isEmpty()&&!error.equals("0")&&!error.equals("false"))throw new IOException("Каталог не вернул серии");}else r.skipValue();continue;}response=true;if(r.peek()!=JsonToken.BEGIN_ARRAY)throw new IOException("Не удалось получить серии");r.beginArray();while(r.hasNext()){if(Thread.currentThread().isInterrupted())throw new InterruptedIOException();if(++records>300000)throw new IOException("Список серий слишком большой");String num="",url="",voice="Озвучка",player="",poster="";int duration=0,opening=0,end=0;r.beginObject();while(r.hasNext()){String key=r.nextName();if(key.equals("number"))num=text(r);else if(key.equals("iframe_url"))url=text(r);else if(key.equals("preview")||key.equals("preview_url")||key.equals("thumbnail")||key.equals("image")||key.equals("screenshot"))poster=image(r);else if(key.equals("duration"))duration=integer(r);else if(key.equals("data")&&r.peek()==JsonToken.BEGIN_OBJECT){r.beginObject();while(r.hasNext()){String k=r.nextName();if(k.equals("dubbing"))voice=text(r);else if(k.equals("player"))player=text(r);else if(k.equals("preview")||k.equals("preview_url")||k.equals("thumbnail")||k.equals("image")||k.equals("screenshot"))poster=image(r);else r.skipValue();}r.endObject();}else if(key.equals("skips")&&r.peek()==JsonToken.BEGIN_OBJECT){r.beginObject();while(r.hasNext()){String skip=r.nextName();if(skip.equals("opening")&&r.peek()==JsonToken.BEGIN_OBJECT){int length=0;r.beginObject();while(r.hasNext()){String k=r.nextName();if(k.equals("time"))opening=integer(r);else if(k.equals("length"))length=integer(r);else r.skipValue();}r.endObject();end=opening+length;}else r.skipValue();}r.endObject();}else r.skipValue();}r.endObject();double ordinal;try{ordinal=Double.parseDouble(num);}catch(Exception e){continue;}String safe=ApiRepository.embed(url);if(!Double.isFinite(ordinal)||ordinal<0||ordinal>100000||safe.isEmpty())continue;Anime.Episode ep=groups.get(ordinal);if(ep==null){ep=new Anime.Episode();ep.id=id+"-"+ordinal;ep.number=ordinal;ep.poster=ApiRepository.safeUrl(poster);groups.put(ordinal,ep);seen.put(ordinal,new HashSet<>());}else if(ep.poster.isEmpty())ep.poster=ApiRepository.safeUrl(poster);if(!seen.get(ordinal).add(voice+"|"+safe))continue;Anime.Variant v=new Anime.Variant(ApiRepository.cleanLabel(voice),ApiRepository.cleanLabel(player),safe);v.duration=duration;v.openingStart=opening;v.openingEnd=end;ep.variants.add(v);ep.duration=Math.max(ep.duration,duration);}
            r.endArray();}r.endObject();if(!response)throw new IOException("Tsuyu не вернул список серий");}catch(Net.HttpCode e){throw new IOException("Каталог временно не ответил");}
        ArrayList<Anime.Episode> result=new ArrayList<>(groups.values());for(Anime.Episode ep:result){ep.variants.sort(Comparator.comparingInt(v->voicePriority(v.name)*100+playerPriority(v.player)));HashMap<String,Integer> versions=new HashMap<>();for(Anime.Variant v:ep.variants){String player=cleanPlayer(v.player);String key=v.name+"|"+player;int n=versions.getOrDefault(key,0)+1;versions.put(key,n);v.displayName=v.name+(player.isEmpty()?"":" · "+player)+(n>1?" · вариант "+n:"");}}return result;
    }
    private static int voicePriority(String name){String v=(name==null?"":name).toLowerCase(Locale.ROOT);return v.contains(Sec.s("351d1c1410250a1006"))?0:v.contains(Sec.s("351d1c151c31170a13"))?1:v.contains(Sec.s("2707001d1c3c4501130b10"))?2:5;}
    private static int playerPriority(String name){String v=(name==null?"":name).toLowerCase(Locale.ROOT);if(v.contains(Sec.s("37051d"))||v.contains(Sec.s("37171b0f1c37000c1a1016")))return 0;if(v.contains(Sec.s("3f1c11101e")))return 1;if(v.contains(Sec.s("3518061607")))return 2;if(v.contains("vk")||v.contains("вконт"))return 3;if(v.contains("rutube"))return 4;if(v.contains("zedfilm")||v.contains("hlamer"))return 5;if(v.contains(Sec.s("351f19161d32")))return 6;if(v.contains(Sec.s("271a17171027")))return 7;return 20;}
    private static String cleanPlayer(String name){String v=name==null?"":name.trim();String l=v.toLowerCase(Locale.ROOT);if(v.equalsIgnoreCase("null"))return "";if(l.contains(Sec.s("3f1c11101e"))||l.contains(Sec.s("351d1c081c27")))return "Tsuyu";if(l.contains(Sec.s("37051d"))||l.contains(Sec.s("37171b0f1c37000c1a1016"))||l.contains(Sec.s("2d0618140c"))||l.contains(Sec.s("2d121b10")))return "Tsuyu";return v;}
    private static String image(JsonReader r)throws IOException{JsonToken t=r.peek();if(t==JsonToken.NULL){r.nextNull();return "";}if(t==JsonToken.STRING||t==JsonToken.NUMBER||t==JsonToken.BOOLEAN)return text(r);if(t==JsonToken.BEGIN_OBJECT){String out="";r.beginObject();while(r.hasNext()){String k=r.nextName();if((k.equals("url")||k.equals("src")||k.equals("preview")||k.equals("preview_url")||k.equals("thumbnail")||k.equals("image")||k.equals("screenshot"))&&out.isEmpty())out=image(r);else r.skipValue();}r.endObject();return out;}r.skipValue();return "";}
    private static String text(JsonReader r)throws IOException{if(r.peek()==JsonToken.NULL){r.nextNull();return "";}if(r.peek()==JsonToken.BOOLEAN)return String.valueOf(r.nextBoolean());return r.nextString();}
    private static int integer(JsonReader r)throws IOException{try{return (int)Math.max(0,Double.parseDouble(text(r)));}catch(NumberFormatException e){return 0;}}
}
