package com.tsuyu.line;

import android.net.Uri;
import android.text.TextUtils;
import org.json.JSONObject;

final class YummyFrame {
    static final String BASE="https://appassets.androidplatform.net/yoru-player/";
    static String html(String url,String nonce,int startSeconds,double episode){
        Uri uri=Uri.parse(url);String origin=uri.getScheme()+"://"+uri.getAuthority();
        String script="(function(){var f=document.getElementById('yummy'),secret="+JSONObject.quote(nonce)+",origin="+JSONObject.quote(origin)+",time=0,duration=0,active=false,seek="+Math.max(0,startSeconds)+",seen={};function send(x){try{x.n=secret;YoruPlayback.onEvent(JSON.stringify(x));}catch(e){}}function sniff(u){try{if(!u)return;u=String(u);if(!/^https?:|^\\/\\//i.test(u)||seen[u])return;seen[u]=1;send({kind:'url',url:u});}catch(e){}}function command(x){try{f.contentWindow.postMessage({key:'kodik_player_api',value:x},origin);}catch(e){}}function report(){send({kind:'time',time:time,duration:duration,playing:active});}function hooks(){try{var of=window.fetch;if(of&&!of.__yoru){var nf=function(i){sniff(typeof i==='string'?i:i&&i.url);return of.apply(this,arguments).then(function(r){sniff(r&&r.url);return r;});};nf.__yoru=1;window.fetch=nf;}}catch(e){}try{var xo=XMLHttpRequest.prototype.open;if(xo&&!xo.__yoru){XMLHttpRequest.prototype.open=function(m,u){sniff(u);this.addEventListener('load',function(){sniff(this.responseURL);});return xo.apply(this,arguments);};XMLHttpRequest.prototype.open.__yoru=1;}}catch(e){}try{var ws=window.WebSocket;if(ws&&!ws.__yoru){window.WebSocket=function(u,p){sniff(u);return p?new ws(u,p):new ws(u);};window.WebSocket.prototype=ws.prototype;window.WebSocket.__yoru=1;}}catch(e){}try{setInterval(function(){var e=performance.getEntriesByType('resource');for(var i=0;i<e.length;i++)sniff(e[i].name);},1200);}catch(e){}}hooks();window.__yoruPause=function(){command({method:'pause'});};window.__yoruPlay=function(){command({method:'play'});};window.__yoruSeek=function(delta){try{var next=Math.max(0,time+Number(delta||0));command({method:'seek',seconds:next});}catch(e){}};f.addEventListener('load',function(){send({kind:'ready'});sniff(f.src);command({method:'play'});});window.addEventListener('message',function(e){if(e.source!==f.contentWindow||e.origin!==origin||!e.data||typeof e.data!=='object')return;try{sniff(e.data.url||e.data.src||e.data.file);}catch(x){}var k=e.data.key,v=e.data.value;if(v&&typeof v==='object')try{sniff(v.url||v.src||v.file||v.link);}catch(x){}if(k==='kodik_player_current_episode'&&v){send({kind:'episode',episode:Number(v.episode),season:Number(v.season)});}else if(k==='kodik_player_duration_update'){duration=Number(v)||0;report();}else if(k==='kodik_player_time_update'){time=typeof v==='number'?v:Number(v&&v.time)||0;report();}else if(k==='kodik_player_play'||k==='kodik_player_video_started'){active=true;send({kind:'state',playing:true});if(seek>3){command({method:'seek',seconds:seek});seek=0;}report();}else if(k==='kodik_player_pause'){active=false;send({kind:'state',playing:false});report();}else if(k==='kodik_player_video_ended'){active=false;report();send({kind:'ended'});}});})();";
        return "<!doctype html><html lang=\"ru\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\"><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#000}iframe{position:fixed;inset:0;width:100%;height:100%;border:0;background:#000}</style></head><body><iframe id=\"yummy\" src=\""+TextUtils.htmlEncode(url)+"\" title=\"Tsuyu\" allow=\"autoplay; fullscreen; picture-in-picture; encrypted-media\" allowfullscreen referrerpolicy=\"no-referrer\" sandbox=\"allow-scripts allow-same-origin allow-forms allow-presentation\"></iframe><script>"+script+"</script></body></html>";
    }
}
